/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Configs implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        key;
    private String        value;
    private String        description;
    private String        category;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;
    private String        publicconfig;

    public Configs() {}

    public Configs(Configs value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
        this.description = value.description;
        this.category = value.category;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
        this.publicconfig = value.publicconfig;
    }

    public Configs(
        Integer       id,
        String        key,
        String        value,
        String        description,
        String        category,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby,
        String        publicconfig
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.description = description;
        this.category = category;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.publicconfig = publicconfig;
    }

    /**
     * Getter for <code>public.Configs.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.Configs.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.Configs.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>public.Configs.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>public.Configs.value</code>.
     */
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>public.Configs.value</code>.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>public.Configs.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.Configs.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.Configs.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.Configs.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.Configs.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.Configs.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.Configs.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.Configs.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.Configs.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.Configs.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.Configs.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.Configs.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.Configs.publicConfig</code>.
     */
    public String getPublicconfig() {
        return this.publicconfig;
    }

    /**
     * Setter for <code>public.Configs.publicConfig</code>.
     */
    public void setPublicconfig(String publicconfig) {
        this.publicconfig = publicconfig;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Configs (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(description);
        sb.append(", ").append(category);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);
        sb.append(", ").append(publicconfig);

        sb.append(")");
        return sb.toString();
    }
}
