/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Drivingdistances implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer distancesid;
    private Integer workorderid;
    private Double  drivingdistanceinmiles;

    public Drivingdistances() {}

    public Drivingdistances(Drivingdistances value) {
        this.distancesid = value.distancesid;
        this.workorderid = value.workorderid;
        this.drivingdistanceinmiles = value.drivingdistanceinmiles;
    }

    public Drivingdistances(
        Integer distancesid,
        Integer workorderid,
        Double  drivingdistanceinmiles
    ) {
        this.distancesid = distancesid;
        this.workorderid = workorderid;
        this.drivingdistanceinmiles = drivingdistanceinmiles;
    }

    /**
     * Getter for <code>public.DrivingDistances.distancesID</code>.
     */
    public Integer getDistancesid() {
        return this.distancesid;
    }

    /**
     * Setter for <code>public.DrivingDistances.distancesID</code>.
     */
    public void setDistancesid(Integer distancesid) {
        this.distancesid = distancesid;
    }

    /**
     * Getter for <code>public.DrivingDistances.workOrderId</code>.
     */
    public Integer getWorkorderid() {
        return this.workorderid;
    }

    /**
     * Setter for <code>public.DrivingDistances.workOrderId</code>.
     */
    public void setWorkorderid(Integer workorderid) {
        this.workorderid = workorderid;
    }

    /**
     * Getter for <code>public.DrivingDistances.drivingDistanceInMiles</code>.
     */
    public Double getDrivingdistanceinmiles() {
        return this.drivingdistanceinmiles;
    }

    /**
     * Setter for <code>public.DrivingDistances.drivingDistanceInMiles</code>.
     */
    public void setDrivingdistanceinmiles(Double drivingdistanceinmiles) {
        this.drivingdistanceinmiles = drivingdistanceinmiles;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Drivingdistances (");

        sb.append(distancesid);
        sb.append(", ").append(workorderid);
        sb.append(", ").append(drivingdistanceinmiles);

        sb.append(")");
        return sb.toString();
    }
}
