/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Emails implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        emailfrom;
    private String        emailto;
    private String        subject;
    private String        body;
    private Integer       transmitattempts;
    private Integer       statusid;
    private LocalDateTime lastattempt;
    private String        attachment;
    private String        attachmentcontenttype;
    private LocalDateTime rowversion;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;

    public Emails() {}

    public Emails(Emails value) {
        this.id = value.id;
        this.emailfrom = value.emailfrom;
        this.emailto = value.emailto;
        this.subject = value.subject;
        this.body = value.body;
        this.transmitattempts = value.transmitattempts;
        this.statusid = value.statusid;
        this.lastattempt = value.lastattempt;
        this.attachment = value.attachment;
        this.attachmentcontenttype = value.attachmentcontenttype;
        this.rowversion = value.rowversion;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
    }

    public Emails(
        Integer       id,
        String        emailfrom,
        String        emailto,
        String        subject,
        String        body,
        Integer       transmitattempts,
        Integer       statusid,
        LocalDateTime lastattempt,
        String        attachment,
        String        attachmentcontenttype,
        LocalDateTime rowversion,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby
    ) {
        this.id = id;
        this.emailfrom = emailfrom;
        this.emailto = emailto;
        this.subject = subject;
        this.body = body;
        this.transmitattempts = transmitattempts;
        this.statusid = statusid;
        this.lastattempt = lastattempt;
        this.attachment = attachment;
        this.attachmentcontenttype = attachmentcontenttype;
        this.rowversion = rowversion;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.Emails.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.Emails.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.Emails.emailFrom</code>.
     */
    public String getEmailfrom() {
        return this.emailfrom;
    }

    /**
     * Setter for <code>public.Emails.emailFrom</code>.
     */
    public void setEmailfrom(String emailfrom) {
        this.emailfrom = emailfrom;
    }

    /**
     * Getter for <code>public.Emails.emailTo</code>.
     */
    public String getEmailto() {
        return this.emailto;
    }

    /**
     * Setter for <code>public.Emails.emailTo</code>.
     */
    public void setEmailto(String emailto) {
        this.emailto = emailto;
    }

    /**
     * Getter for <code>public.Emails.subject</code>.
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     * Setter for <code>public.Emails.subject</code>.
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * Getter for <code>public.Emails.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Setter for <code>public.Emails.body</code>.
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Getter for <code>public.Emails.transmitAttempts</code>.
     */
    public Integer getTransmitattempts() {
        return this.transmitattempts;
    }

    /**
     * Setter for <code>public.Emails.transmitAttempts</code>.
     */
    public void setTransmitattempts(Integer transmitattempts) {
        this.transmitattempts = transmitattempts;
    }

    /**
     * Getter for <code>public.Emails.statusID</code>.
     */
    public Integer getStatusid() {
        return this.statusid;
    }

    /**
     * Setter for <code>public.Emails.statusID</code>.
     */
    public void setStatusid(Integer statusid) {
        this.statusid = statusid;
    }

    /**
     * Getter for <code>public.Emails.lastAttempt</code>.
     */
    public LocalDateTime getLastattempt() {
        return this.lastattempt;
    }

    /**
     * Setter for <code>public.Emails.lastAttempt</code>.
     */
    public void setLastattempt(LocalDateTime lastattempt) {
        this.lastattempt = lastattempt;
    }

    /**
     * Getter for <code>public.Emails.attachment</code>.
     */
    public String getAttachment() {
        return this.attachment;
    }

    /**
     * Setter for <code>public.Emails.attachment</code>.
     */
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }

    /**
     * Getter for <code>public.Emails.attachmentContentType</code>.
     */
    public String getAttachmentcontenttype() {
        return this.attachmentcontenttype;
    }

    /**
     * Setter for <code>public.Emails.attachmentContentType</code>.
     */
    public void setAttachmentcontenttype(String attachmentcontenttype) {
        this.attachmentcontenttype = attachmentcontenttype;
    }

    /**
     * Getter for <code>public.Emails.RowVersion</code>.
     */
    public LocalDateTime getRowversion() {
        return this.rowversion;
    }

    /**
     * Setter for <code>public.Emails.RowVersion</code>.
     */
    public void setRowversion(LocalDateTime rowversion) {
        this.rowversion = rowversion;
    }

    /**
     * Getter for <code>public.Emails.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.Emails.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.Emails.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.Emails.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.Emails.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.Emails.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.Emails.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.Emails.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Emails (");

        sb.append(id);
        sb.append(", ").append(emailfrom);
        sb.append(", ").append(emailto);
        sb.append(", ").append(subject);
        sb.append(", ").append(body);
        sb.append(", ").append(transmitattempts);
        sb.append(", ").append(statusid);
        sb.append(", ").append(lastattempt);
        sb.append(", ").append(attachment);
        sb.append(", ").append(attachmentcontenttype);
        sb.append(", ").append(rowversion);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);

        sb.append(")");
        return sb.toString();
    }
}
