/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Joineventimage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;
    private Integer       eventid;
    private Integer       imageid;

    public Joineventimage() {}

    public Joineventimage(Joineventimage value) {
        this.id = value.id;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
        this.eventid = value.eventid;
        this.imageid = value.imageid;
    }

    public Joineventimage(
        Integer       id,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby,
        Integer       eventid,
        Integer       imageid
    ) {
        this.id = id;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.eventid = eventid;
        this.imageid = imageid;
    }

    /**
     * Getter for <code>public.JoinEventImage.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.JoinEventImage.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.JoinEventImage.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.JoinEventImage.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.JoinEventImage.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.JoinEventImage.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.JoinEventImage.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.JoinEventImage.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.JoinEventImage.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.JoinEventImage.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.JoinEventImage.EventID</code>.
     */
    public Integer getEventid() {
        return this.eventid;
    }

    /**
     * Setter for <code>public.JoinEventImage.EventID</code>.
     */
    public void setEventid(Integer eventid) {
        this.eventid = eventid;
    }

    /**
     * Getter for <code>public.JoinEventImage.ImageID</code>.
     */
    public Integer getImageid() {
        return this.imageid;
    }

    /**
     * Setter for <code>public.JoinEventImage.ImageID</code>.
     */
    public void setImageid(Integer imageid) {
        this.imageid = imageid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Joineventimage (");

        sb.append(id);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);
        sb.append(", ").append(eventid);
        sb.append(", ").append(imageid);

        sb.append(")");
        return sb.toString();
    }
}
