/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reportdefinitions implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        name;
    private String        commonname;
    private String        title;
    private String        description;
    private String        sqlquery;
    private String        category;
    private String        subcategory;
    private String        inputsjson;
    private String        columnsjson;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;

    public Reportdefinitions() {}

    public Reportdefinitions(Reportdefinitions value) {
        this.id = value.id;
        this.name = value.name;
        this.commonname = value.commonname;
        this.title = value.title;
        this.description = value.description;
        this.sqlquery = value.sqlquery;
        this.category = value.category;
        this.subcategory = value.subcategory;
        this.inputsjson = value.inputsjson;
        this.columnsjson = value.columnsjson;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
    }

    public Reportdefinitions(
        Integer       id,
        String        name,
        String        commonname,
        String        title,
        String        description,
        String        sqlquery,
        String        category,
        String        subcategory,
        String        inputsjson,
        String        columnsjson,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby
    ) {
        this.id = id;
        this.name = name;
        this.commonname = commonname;
        this.title = title;
        this.description = description;
        this.sqlquery = sqlquery;
        this.category = category;
        this.subcategory = subcategory;
        this.inputsjson = inputsjson;
        this.columnsjson = columnsjson;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.ReportDefinitions.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ReportDefinitions.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.ReportDefinitions.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.ReportDefinitions.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.ReportDefinitions.commonName</code>.
     */
    public String getCommonname() {
        return this.commonname;
    }

    /**
     * Setter for <code>public.ReportDefinitions.commonName</code>.
     */
    public void setCommonname(String commonname) {
        this.commonname = commonname;
    }

    /**
     * Getter for <code>public.ReportDefinitions.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.ReportDefinitions.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.ReportDefinitions.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.ReportDefinitions.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.ReportDefinitions.sqlquery</code>.
     */
    public String getSqlquery() {
        return this.sqlquery;
    }

    /**
     * Setter for <code>public.ReportDefinitions.sqlquery</code>.
     */
    public void setSqlquery(String sqlquery) {
        this.sqlquery = sqlquery;
    }

    /**
     * Getter for <code>public.ReportDefinitions.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.ReportDefinitions.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.ReportDefinitions.subcategory</code>.
     */
    public String getSubcategory() {
        return this.subcategory;
    }

    /**
     * Setter for <code>public.ReportDefinitions.subcategory</code>.
     */
    public void setSubcategory(String subcategory) {
        this.subcategory = subcategory;
    }

    /**
     * Getter for <code>public.ReportDefinitions.inputsJson</code>.
     */
    public String getInputsjson() {
        return this.inputsjson;
    }

    /**
     * Setter for <code>public.ReportDefinitions.inputsJson</code>.
     */
    public void setInputsjson(String inputsjson) {
        this.inputsjson = inputsjson;
    }

    /**
     * Getter for <code>public.ReportDefinitions.columnsJson</code>.
     */
    public String getColumnsjson() {
        return this.columnsjson;
    }

    /**
     * Setter for <code>public.ReportDefinitions.columnsJson</code>.
     */
    public void setColumnsjson(String columnsjson) {
        this.columnsjson = columnsjson;
    }

    /**
     * Getter for <code>public.ReportDefinitions.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.ReportDefinitions.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.ReportDefinitions.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.ReportDefinitions.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.ReportDefinitions.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.ReportDefinitions.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.ReportDefinitions.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.ReportDefinitions.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Reportdefinitions (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(commonname);
        sb.append(", ").append(title);
        sb.append(", ").append(description);
        sb.append(", ").append(sqlquery);
        sb.append(", ").append(category);
        sb.append(", ").append(subcategory);
        sb.append(", ").append(inputsjson);
        sb.append(", ").append(columnsjson);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);

        sb.append(")");
        return sb.toString();
    }
}
