/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Schedulerules implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       day;
    private Integer       leadhours;
    private Integer       minstartmin;
    private Integer       maxendmin;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;

    public Schedulerules() {}

    public Schedulerules(Schedulerules value) {
        this.id = value.id;
        this.day = value.day;
        this.leadhours = value.leadhours;
        this.minstartmin = value.minstartmin;
        this.maxendmin = value.maxendmin;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
    }

    public Schedulerules(
        Integer       id,
        Integer       day,
        Integer       leadhours,
        Integer       minstartmin,
        Integer       maxendmin,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby
    ) {
        this.id = id;
        this.day = day;
        this.leadhours = leadhours;
        this.minstartmin = minstartmin;
        this.maxendmin = maxendmin;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.ScheduleRules.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.ScheduleRules.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.ScheduleRules.day</code>.
     */
    public Integer getDay() {
        return this.day;
    }

    /**
     * Setter for <code>public.ScheduleRules.day</code>.
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * Getter for <code>public.ScheduleRules.leadHours</code>.
     */
    public Integer getLeadhours() {
        return this.leadhours;
    }

    /**
     * Setter for <code>public.ScheduleRules.leadHours</code>.
     */
    public void setLeadhours(Integer leadhours) {
        this.leadhours = leadhours;
    }

    /**
     * Getter for <code>public.ScheduleRules.minStartMin</code>.
     */
    public Integer getMinstartmin() {
        return this.minstartmin;
    }

    /**
     * Setter for <code>public.ScheduleRules.minStartMin</code>.
     */
    public void setMinstartmin(Integer minstartmin) {
        this.minstartmin = minstartmin;
    }

    /**
     * Getter for <code>public.ScheduleRules.maxEndMin</code>.
     */
    public Integer getMaxendmin() {
        return this.maxendmin;
    }

    /**
     * Setter for <code>public.ScheduleRules.maxEndMin</code>.
     */
    public void setMaxendmin(Integer maxendmin) {
        this.maxendmin = maxendmin;
    }

    /**
     * Getter for <code>public.ScheduleRules.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.ScheduleRules.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.ScheduleRules.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.ScheduleRules.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.ScheduleRules.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.ScheduleRules.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.ScheduleRules.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.ScheduleRules.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Schedulerules (");

        sb.append(id);
        sb.append(", ").append(day);
        sb.append(", ").append(leadhours);
        sb.append(", ").append(minstartmin);
        sb.append(", ").append(maxendmin);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);

        sb.append(")");
        return sb.toString();
    }
}
