/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transportprovideravailabilities implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       transportproviderid;
    private String        key;
    private String        lookupkey;
    private Integer       day;
    private String        available;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;

    public Transportprovideravailabilities() {}

    public Transportprovideravailabilities(Transportprovideravailabilities value) {
        this.id = value.id;
        this.transportproviderid = value.transportproviderid;
        this.key = value.key;
        this.lookupkey = value.lookupkey;
        this.day = value.day;
        this.available = value.available;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
    }

    public Transportprovideravailabilities(
        Integer       id,
        Integer       transportproviderid,
        String        key,
        String        lookupkey,
        Integer       day,
        String        available,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby
    ) {
        this.id = id;
        this.transportproviderid = transportproviderid;
        this.key = key;
        this.lookupkey = lookupkey;
        this.day = day;
        this.available = available;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.transportProviderID</code>.
     */
    public Integer getTransportproviderid() {
        return this.transportproviderid;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.transportProviderID</code>.
     */
    public void setTransportproviderid(Integer transportproviderid) {
        this.transportproviderid = transportproviderid;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.key</code>.
     */
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.key</code>.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.lookupKey</code>.
     */
    public String getLookupkey() {
        return this.lookupkey;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.lookupKey</code>.
     */
    public void setLookupkey(String lookupkey) {
        this.lookupkey = lookupkey;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.day</code>.
     */
    public Integer getDay() {
        return this.day;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.day</code>.
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.available</code>.
     */
    public String getAvailable() {
        return this.available;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.available</code>.
     */
    public void setAvailable(String available) {
        this.available = available;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.TransportProviderAvailabilities.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.TransportProviderAvailabilities.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transportprovideravailabilities (");

        sb.append(id);
        sb.append(", ").append(transportproviderid);
        sb.append(", ").append(key);
        sb.append(", ").append(lookupkey);
        sb.append(", ").append(day);
        sb.append(", ").append(available);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);

        sb.append(")");
        return sb.toString();
    }
}
