/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workersignins implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       dwccardnum;
    private Integer       workerid;
    private Integer       workassignmentid;
    private LocalDateTime dateforsignin;
    private LocalDateTime lotteryTimestamp;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;
    private Integer       memberstatus;
    private Integer       lotterySequence;
    private Double        timezoneoffset;

    public Workersignins() {}

    public Workersignins(Workersignins value) {
        this.id = value.id;
        this.dwccardnum = value.dwccardnum;
        this.workerid = value.workerid;
        this.workassignmentid = value.workassignmentid;
        this.dateforsignin = value.dateforsignin;
        this.lotteryTimestamp = value.lotteryTimestamp;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
        this.memberstatus = value.memberstatus;
        this.lotterySequence = value.lotterySequence;
        this.timezoneoffset = value.timezoneoffset;
    }

    public Workersignins(
        Integer       id,
        Integer       dwccardnum,
        Integer       workerid,
        Integer       workassignmentid,
        LocalDateTime dateforsignin,
        LocalDateTime lotteryTimestamp,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby,
        Integer       memberstatus,
        Integer       lotterySequence,
        Double        timezoneoffset
    ) {
        this.id = id;
        this.dwccardnum = dwccardnum;
        this.workerid = workerid;
        this.workassignmentid = workassignmentid;
        this.dateforsignin = dateforsignin;
        this.lotteryTimestamp = lotteryTimestamp;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.memberstatus = memberstatus;
        this.lotterySequence = lotterySequence;
        this.timezoneoffset = timezoneoffset;
    }

    /**
     * Getter for <code>public.WorkerSignins.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.WorkerSignins.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.WorkerSignins.dwccardnum</code>.
     */
    public Integer getDwccardnum() {
        return this.dwccardnum;
    }

    /**
     * Setter for <code>public.WorkerSignins.dwccardnum</code>.
     */
    public void setDwccardnum(Integer dwccardnum) {
        this.dwccardnum = dwccardnum;
    }

    /**
     * Getter for <code>public.WorkerSignins.WorkerID</code>.
     */
    public Integer getWorkerid() {
        return this.workerid;
    }

    /**
     * Setter for <code>public.WorkerSignins.WorkerID</code>.
     */
    public void setWorkerid(Integer workerid) {
        this.workerid = workerid;
    }

    /**
     * Getter for <code>public.WorkerSignins.WorkAssignmentID</code>.
     */
    public Integer getWorkassignmentid() {
        return this.workassignmentid;
    }

    /**
     * Setter for <code>public.WorkerSignins.WorkAssignmentID</code>.
     */
    public void setWorkassignmentid(Integer workassignmentid) {
        this.workassignmentid = workassignmentid;
    }

    /**
     * Getter for <code>public.WorkerSignins.dateforsignin</code>.
     */
    public LocalDateTime getDateforsignin() {
        return this.dateforsignin;
    }

    /**
     * Setter for <code>public.WorkerSignins.dateforsignin</code>.
     */
    public void setDateforsignin(LocalDateTime dateforsignin) {
        this.dateforsignin = dateforsignin;
    }

    /**
     * Getter for <code>public.WorkerSignins.lottery_timestamp</code>.
     */
    public LocalDateTime getLotteryTimestamp() {
        return this.lotteryTimestamp;
    }

    /**
     * Setter for <code>public.WorkerSignins.lottery_timestamp</code>.
     */
    public void setLotteryTimestamp(LocalDateTime lotteryTimestamp) {
        this.lotteryTimestamp = lotteryTimestamp;
    }

    /**
     * Getter for <code>public.WorkerSignins.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.WorkerSignins.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.WorkerSignins.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.WorkerSignins.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.WorkerSignins.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.WorkerSignins.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.WorkerSignins.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.WorkerSignins.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.WorkerSignins.memberStatus</code>.
     */
    public Integer getMemberstatus() {
        return this.memberstatus;
    }

    /**
     * Setter for <code>public.WorkerSignins.memberStatus</code>.
     */
    public void setMemberstatus(Integer memberstatus) {
        this.memberstatus = memberstatus;
    }

    /**
     * Getter for <code>public.WorkerSignins.lottery_sequence</code>.
     */
    public Integer getLotterySequence() {
        return this.lotterySequence;
    }

    /**
     * Setter for <code>public.WorkerSignins.lottery_sequence</code>.
     */
    public void setLotterySequence(Integer lotterySequence) {
        this.lotterySequence = lotterySequence;
    }

    /**
     * Getter for <code>public.WorkerSignins.timeZoneOffset</code>.
     */
    public Double getTimezoneoffset() {
        return this.timezoneoffset;
    }

    /**
     * Setter for <code>public.WorkerSignins.timeZoneOffset</code>.
     */
    public void setTimezoneoffset(Double timezoneoffset) {
        this.timezoneoffset = timezoneoffset;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workersignins (");

        sb.append(id);
        sb.append(", ").append(dwccardnum);
        sb.append(", ").append(workerid);
        sb.append(", ").append(workassignmentid);
        sb.append(", ").append(dateforsignin);
        sb.append(", ").append(lotteryTimestamp);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);
        sb.append(", ").append(memberstatus);
        sb.append(", ").append(lotterySequence);
        sb.append(", ").append(timezoneoffset);

        sb.append(")");
        return sb.toString();
    }
}
