/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workerrequests implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       workorderid;
    private Integer       workerid;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;

    public Workerrequests() {}

    public Workerrequests(Workerrequests value) {
        this.id = value.id;
        this.workorderid = value.workorderid;
        this.workerid = value.workerid;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
    }

    public Workerrequests(
        Integer       id,
        Integer       workorderid,
        Integer       workerid,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby
    ) {
        this.id = id;
        this.workorderid = workorderid;
        this.workerid = workerid;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.WorkerRequests.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.WorkerRequests.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.WorkerRequests.WorkOrderID</code>.
     */
    public Integer getWorkorderid() {
        return this.workorderid;
    }

    /**
     * Setter for <code>public.WorkerRequests.WorkOrderID</code>.
     */
    public void setWorkorderid(Integer workorderid) {
        this.workorderid = workorderid;
    }

    /**
     * Getter for <code>public.WorkerRequests.WorkerID</code>.
     */
    public Integer getWorkerid() {
        return this.workerid;
    }

    /**
     * Setter for <code>public.WorkerRequests.WorkerID</code>.
     */
    public void setWorkerid(Integer workerid) {
        this.workerid = workerid;
    }

    /**
     * Getter for <code>public.WorkerRequests.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.WorkerRequests.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.WorkerRequests.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.WorkerRequests.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.WorkerRequests.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.WorkerRequests.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.WorkerRequests.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.WorkerRequests.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workerrequests (");

        sb.append(id);
        sb.append(", ").append(workorderid);
        sb.append(", ").append(workerid);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);

        sb.append(")");
        return sb.toString();
    }
}
