/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workassignments implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       workerassignedid;
    private Integer       workorderid;
    private Integer       workersigninid;
    private String        active;
    private Integer       pseudoid;
    private String        description;
    private Integer       englishlevelid;
    private Integer       skillid;
    private Double        hourlywage;
    private Double        hours;
    private Integer       hourrange;
    private Integer       days;
    private Integer       qualityofwork;
    private Integer       followdirections;
    private Integer       attitude;
    private Integer       reliability;
    private Integer       transportprogram;
    private String        comments;
    private LocalDateTime datecreated;
    private LocalDateTime dateupdated;
    private String        createdby;
    private String        updatedby;
    private Double        surcharge;
    private Integer       workerrating;
    private String        workerratingcomments;
    private String        weightlifted;
    private String        skillen;
    private String        skilles;
    private String        fullwaid;
    private Double        minearnings;
    private Double        maxearnings;
    private Double        transportcost;

    public Workassignments() {}

    public Workassignments(Workassignments value) {
        this.id = value.id;
        this.workerassignedid = value.workerassignedid;
        this.workorderid = value.workorderid;
        this.workersigninid = value.workersigninid;
        this.active = value.active;
        this.pseudoid = value.pseudoid;
        this.description = value.description;
        this.englishlevelid = value.englishlevelid;
        this.skillid = value.skillid;
        this.hourlywage = value.hourlywage;
        this.hours = value.hours;
        this.hourrange = value.hourrange;
        this.days = value.days;
        this.qualityofwork = value.qualityofwork;
        this.followdirections = value.followdirections;
        this.attitude = value.attitude;
        this.reliability = value.reliability;
        this.transportprogram = value.transportprogram;
        this.comments = value.comments;
        this.datecreated = value.datecreated;
        this.dateupdated = value.dateupdated;
        this.createdby = value.createdby;
        this.updatedby = value.updatedby;
        this.surcharge = value.surcharge;
        this.workerrating = value.workerrating;
        this.workerratingcomments = value.workerratingcomments;
        this.weightlifted = value.weightlifted;
        this.skillen = value.skillen;
        this.skilles = value.skilles;
        this.fullwaid = value.fullwaid;
        this.minearnings = value.minearnings;
        this.maxearnings = value.maxearnings;
        this.transportcost = value.transportcost;
    }

    public Workassignments(
        Integer       id,
        Integer       workerassignedid,
        Integer       workorderid,
        Integer       workersigninid,
        String        active,
        Integer       pseudoid,
        String        description,
        Integer       englishlevelid,
        Integer       skillid,
        Double        hourlywage,
        Double        hours,
        Integer       hourrange,
        Integer       days,
        Integer       qualityofwork,
        Integer       followdirections,
        Integer       attitude,
        Integer       reliability,
        Integer       transportprogram,
        String        comments,
        LocalDateTime datecreated,
        LocalDateTime dateupdated,
        String        createdby,
        String        updatedby,
        Double        surcharge,
        Integer       workerrating,
        String        workerratingcomments,
        String        weightlifted,
        String        skillen,
        String        skilles,
        String        fullwaid,
        Double        minearnings,
        Double        maxearnings,
        Double        transportcost
    ) {
        this.id = id;
        this.workerassignedid = workerassignedid;
        this.workorderid = workorderid;
        this.workersigninid = workersigninid;
        this.active = active;
        this.pseudoid = pseudoid;
        this.description = description;
        this.englishlevelid = englishlevelid;
        this.skillid = skillid;
        this.hourlywage = hourlywage;
        this.hours = hours;
        this.hourrange = hourrange;
        this.days = days;
        this.qualityofwork = qualityofwork;
        this.followdirections = followdirections;
        this.attitude = attitude;
        this.reliability = reliability;
        this.transportprogram = transportprogram;
        this.comments = comments;
        this.datecreated = datecreated;
        this.dateupdated = dateupdated;
        this.createdby = createdby;
        this.updatedby = updatedby;
        this.surcharge = surcharge;
        this.workerrating = workerrating;
        this.workerratingcomments = workerratingcomments;
        this.weightlifted = weightlifted;
        this.skillen = skillen;
        this.skilles = skilles;
        this.fullwaid = fullwaid;
        this.minearnings = minearnings;
        this.maxearnings = maxearnings;
        this.transportcost = transportcost;
    }

    /**
     * Getter for <code>public.WorkAssignments.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.WorkAssignments.id</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.WorkAssignments.workerAssignedID</code>.
     */
    public Integer getWorkerassignedid() {
        return this.workerassignedid;
    }

    /**
     * Setter for <code>public.WorkAssignments.workerAssignedID</code>.
     */
    public void setWorkerassignedid(Integer workerassignedid) {
        this.workerassignedid = workerassignedid;
    }

    /**
     * Getter for <code>public.WorkAssignments.workOrderID</code>.
     */
    public Integer getWorkorderid() {
        return this.workorderid;
    }

    /**
     * Setter for <code>public.WorkAssignments.workOrderID</code>.
     */
    public void setWorkorderid(Integer workorderid) {
        this.workorderid = workorderid;
    }

    /**
     * Getter for <code>public.WorkAssignments.workerSigninID</code>.
     */
    public Integer getWorkersigninid() {
        return this.workersigninid;
    }

    /**
     * Setter for <code>public.WorkAssignments.workerSigninID</code>.
     */
    public void setWorkersigninid(Integer workersigninid) {
        this.workersigninid = workersigninid;
    }

    /**
     * Getter for <code>public.WorkAssignments.active</code>.
     */
    public String getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.WorkAssignments.active</code>.
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * Getter for <code>public.WorkAssignments.pseudoID</code>.
     */
    public Integer getPseudoid() {
        return this.pseudoid;
    }

    /**
     * Setter for <code>public.WorkAssignments.pseudoID</code>.
     */
    public void setPseudoid(Integer pseudoid) {
        this.pseudoid = pseudoid;
    }

    /**
     * Getter for <code>public.WorkAssignments.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.WorkAssignments.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.WorkAssignments.englishLevelID</code>.
     */
    public Integer getEnglishlevelid() {
        return this.englishlevelid;
    }

    /**
     * Setter for <code>public.WorkAssignments.englishLevelID</code>.
     */
    public void setEnglishlevelid(Integer englishlevelid) {
        this.englishlevelid = englishlevelid;
    }

    /**
     * Getter for <code>public.WorkAssignments.skillID</code>.
     */
    public Integer getSkillid() {
        return this.skillid;
    }

    /**
     * Setter for <code>public.WorkAssignments.skillID</code>.
     */
    public void setSkillid(Integer skillid) {
        this.skillid = skillid;
    }

    /**
     * Getter for <code>public.WorkAssignments.hourlyWage</code>.
     */
    public Double getHourlywage() {
        return this.hourlywage;
    }

    /**
     * Setter for <code>public.WorkAssignments.hourlyWage</code>.
     */
    public void setHourlywage(Double hourlywage) {
        this.hourlywage = hourlywage;
    }

    /**
     * Getter for <code>public.WorkAssignments.hours</code>.
     */
    public Double getHours() {
        return this.hours;
    }

    /**
     * Setter for <code>public.WorkAssignments.hours</code>.
     */
    public void setHours(Double hours) {
        this.hours = hours;
    }

    /**
     * Getter for <code>public.WorkAssignments.hourRange</code>.
     */
    public Integer getHourrange() {
        return this.hourrange;
    }

    /**
     * Setter for <code>public.WorkAssignments.hourRange</code>.
     */
    public void setHourrange(Integer hourrange) {
        this.hourrange = hourrange;
    }

    /**
     * Getter for <code>public.WorkAssignments.days</code>.
     */
    public Integer getDays() {
        return this.days;
    }

    /**
     * Setter for <code>public.WorkAssignments.days</code>.
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * Getter for <code>public.WorkAssignments.qualityOfWork</code>.
     */
    public Integer getQualityofwork() {
        return this.qualityofwork;
    }

    /**
     * Setter for <code>public.WorkAssignments.qualityOfWork</code>.
     */
    public void setQualityofwork(Integer qualityofwork) {
        this.qualityofwork = qualityofwork;
    }

    /**
     * Getter for <code>public.WorkAssignments.followDirections</code>.
     */
    public Integer getFollowdirections() {
        return this.followdirections;
    }

    /**
     * Setter for <code>public.WorkAssignments.followDirections</code>.
     */
    public void setFollowdirections(Integer followdirections) {
        this.followdirections = followdirections;
    }

    /**
     * Getter for <code>public.WorkAssignments.attitude</code>.
     */
    public Integer getAttitude() {
        return this.attitude;
    }

    /**
     * Setter for <code>public.WorkAssignments.attitude</code>.
     */
    public void setAttitude(Integer attitude) {
        this.attitude = attitude;
    }

    /**
     * Getter for <code>public.WorkAssignments.reliability</code>.
     */
    public Integer getReliability() {
        return this.reliability;
    }

    /**
     * Setter for <code>public.WorkAssignments.reliability</code>.
     */
    public void setReliability(Integer reliability) {
        this.reliability = reliability;
    }

    /**
     * Getter for <code>public.WorkAssignments.transportProgram</code>.
     */
    public Integer getTransportprogram() {
        return this.transportprogram;
    }

    /**
     * Setter for <code>public.WorkAssignments.transportProgram</code>.
     */
    public void setTransportprogram(Integer transportprogram) {
        this.transportprogram = transportprogram;
    }

    /**
     * Getter for <code>public.WorkAssignments.comments</code>.
     */
    public String getComments() {
        return this.comments;
    }

    /**
     * Setter for <code>public.WorkAssignments.comments</code>.
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * Getter for <code>public.WorkAssignments.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return this.datecreated;
    }

    /**
     * Setter for <code>public.WorkAssignments.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime datecreated) {
        this.datecreated = datecreated;
    }

    /**
     * Getter for <code>public.WorkAssignments.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return this.dateupdated;
    }

    /**
     * Setter for <code>public.WorkAssignments.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime dateupdated) {
        this.dateupdated = dateupdated;
    }

    /**
     * Getter for <code>public.WorkAssignments.Createdby</code>.
     */
    public String getCreatedby() {
        return this.createdby;
    }

    /**
     * Setter for <code>public.WorkAssignments.Createdby</code>.
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }

    /**
     * Getter for <code>public.WorkAssignments.Updatedby</code>.
     */
    public String getUpdatedby() {
        return this.updatedby;
    }

    /**
     * Setter for <code>public.WorkAssignments.Updatedby</code>.
     */
    public void setUpdatedby(String updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * Getter for <code>public.WorkAssignments.surcharge</code>.
     */
    public Double getSurcharge() {
        return this.surcharge;
    }

    /**
     * Setter for <code>public.WorkAssignments.surcharge</code>.
     */
    public void setSurcharge(Double surcharge) {
        this.surcharge = surcharge;
    }

    /**
     * Getter for <code>public.WorkAssignments.workerRating</code>.
     */
    public Integer getWorkerrating() {
        return this.workerrating;
    }

    /**
     * Setter for <code>public.WorkAssignments.workerRating</code>.
     */
    public void setWorkerrating(Integer workerrating) {
        this.workerrating = workerrating;
    }

    /**
     * Getter for <code>public.WorkAssignments.workerRatingComments</code>.
     */
    public String getWorkerratingcomments() {
        return this.workerratingcomments;
    }

    /**
     * Setter for <code>public.WorkAssignments.workerRatingComments</code>.
     */
    public void setWorkerratingcomments(String workerratingcomments) {
        this.workerratingcomments = workerratingcomments;
    }

    /**
     * Getter for <code>public.WorkAssignments.weightLifted</code>.
     */
    public String getWeightlifted() {
        return this.weightlifted;
    }

    /**
     * Setter for <code>public.WorkAssignments.weightLifted</code>.
     */
    public void setWeightlifted(String weightlifted) {
        this.weightlifted = weightlifted;
    }

    /**
     * Getter for <code>public.WorkAssignments.skillEN</code>.
     */
    public String getSkillen() {
        return this.skillen;
    }

    /**
     * Setter for <code>public.WorkAssignments.skillEN</code>.
     */
    public void setSkillen(String skillen) {
        this.skillen = skillen;
    }

    /**
     * Getter for <code>public.WorkAssignments.skillES</code>.
     */
    public String getSkilles() {
        return this.skilles;
    }

    /**
     * Setter for <code>public.WorkAssignments.skillES</code>.
     */
    public void setSkilles(String skilles) {
        this.skilles = skilles;
    }

    /**
     * Getter for <code>public.WorkAssignments.fullWAID</code>.
     */
    public String getFullwaid() {
        return this.fullwaid;
    }

    /**
     * Setter for <code>public.WorkAssignments.fullWAID</code>.
     */
    public void setFullwaid(String fullwaid) {
        this.fullwaid = fullwaid;
    }

    /**
     * Getter for <code>public.WorkAssignments.minEarnings</code>.
     */
    public Double getMinearnings() {
        return this.minearnings;
    }

    /**
     * Setter for <code>public.WorkAssignments.minEarnings</code>.
     */
    public void setMinearnings(Double minearnings) {
        this.minearnings = minearnings;
    }

    /**
     * Getter for <code>public.WorkAssignments.maxEarnings</code>.
     */
    public Double getMaxearnings() {
        return this.maxearnings;
    }

    /**
     * Setter for <code>public.WorkAssignments.maxEarnings</code>.
     */
    public void setMaxearnings(Double maxearnings) {
        this.maxearnings = maxearnings;
    }

    /**
     * Getter for <code>public.WorkAssignments.transportCost</code>.
     */
    public Double getTransportcost() {
        return this.transportcost;
    }

    /**
     * Setter for <code>public.WorkAssignments.transportCost</code>.
     */
    public void setTransportcost(Double transportcost) {
        this.transportcost = transportcost;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Workassignments (");

        sb.append(id);
        sb.append(", ").append(workerassignedid);
        sb.append(", ").append(workorderid);
        sb.append(", ").append(workersigninid);
        sb.append(", ").append(active);
        sb.append(", ").append(pseudoid);
        sb.append(", ").append(description);
        sb.append(", ").append(englishlevelid);
        sb.append(", ").append(skillid);
        sb.append(", ").append(hourlywage);
        sb.append(", ").append(hours);
        sb.append(", ").append(hourrange);
        sb.append(", ").append(days);
        sb.append(", ").append(qualityofwork);
        sb.append(", ").append(followdirections);
        sb.append(", ").append(attitude);
        sb.append(", ").append(reliability);
        sb.append(", ").append(transportprogram);
        sb.append(", ").append(comments);
        sb.append(", ").append(datecreated);
        sb.append(", ").append(dateupdated);
        sb.append(", ").append(createdby);
        sb.append(", ").append(updatedby);
        sb.append(", ").append(surcharge);
        sb.append(", ").append(workerrating);
        sb.append(", ").append(workerratingcomments);
        sb.append(", ").append(weightlifted);
        sb.append(", ").append(skillen);
        sb.append(", ").append(skilles);
        sb.append(", ").append(fullwaid);
        sb.append(", ").append(minearnings);
        sb.append(", ").append(maxearnings);
        sb.append(", ").append(transportcost);

        sb.append(")");
        return sb.toString();
    }
}
