/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.daos;


import com.savagelearning.machete.core.tables.Employers;
import com.savagelearning.machete.core.tables.records.EmployersRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployersDao extends DAOImpl<EmployersRecord, com.savagelearning.machete.core.tables.pojos.Employers, Integer> {

    /**
     * Create a new EmployersDao without any configuration
     */
    public EmployersDao() {
        super(Employers.EMPLOYERS, com.savagelearning.machete.core.tables.pojos.Employers.class);
    }

    /**
     * Create a new EmployersDao with an attached configuration
     */
    public EmployersDao(Configuration configuration) {
        super(Employers.EMPLOYERS, com.savagelearning.machete.core.tables.pojos.Employers.class, configuration);
    }

    @Override
    public Integer getId(com.savagelearning.machete.core.tables.pojos.Employers object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchById(Integer... values) {
        return fetch(Employers.EMPLOYERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.savagelearning.machete.core.tables.pojos.Employers fetchOneById(Integer value) {
        return fetchOne(Employers.EMPLOYERS.ID, value);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfActive(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByActive(String... values) {
        return fetch(Employers.EMPLOYERS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>business BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfBusiness(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.BUSINESS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>business IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByBusiness(String... values) {
        return fetch(Employers.EMPLOYERS.BUSINESS, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByName(String... values) {
        return fetch(Employers.EMPLOYERS.NAME, values);
    }

    /**
     * Fetch records that have <code>address1 BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfAddress1(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ADDRESS1, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address1 IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByAddress1(String... values) {
        return fetch(Employers.EMPLOYERS.ADDRESS1, values);
    }

    /**
     * Fetch records that have <code>address2 BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfAddress2(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ADDRESS2, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>address2 IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByAddress2(String... values) {
        return fetch(Employers.EMPLOYERS.ADDRESS2, values);
    }

    /**
     * Fetch records that have <code>city BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfCity(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.CITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByCity(String... values) {
        return fetch(Employers.EMPLOYERS.CITY, values);
    }

    /**
     * Fetch records that have <code>state BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfState(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByState(String... values) {
        return fetch(Employers.EMPLOYERS.STATE, values);
    }

    /**
     * Fetch records that have <code>phone BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfPhone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.PHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByPhone(String... values) {
        return fetch(Employers.EMPLOYERS.PHONE, values);
    }

    /**
     * Fetch records that have <code>cellphone BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfCellphone(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.CELLPHONE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cellphone IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByCellphone(String... values) {
        return fetch(Employers.EMPLOYERS.CELLPHONE, values);
    }

    /**
     * Fetch records that have <code>zipcode BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfZipcode(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ZIPCODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>zipcode IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByZipcode(String... values) {
        return fetch(Employers.EMPLOYERS.ZIPCODE, values);
    }

    /**
     * Fetch records that have <code>email BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfEmail(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.EMAIL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>email IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByEmail(String... values) {
        return fetch(Employers.EMPLOYERS.EMAIL, values);
    }

    /**
     * Fetch records that have <code>referredby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfReferredby(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.REFERREDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>referredby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByReferredby(Integer... values) {
        return fetch(Employers.EMPLOYERS.REFERREDBY, values);
    }

    /**
     * Fetch records that have <code>referredbyOther BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfReferredbyother(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.REFERREDBYOTHER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>referredbyOther IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByReferredbyother(String... values) {
        return fetch(Employers.EMPLOYERS.REFERREDBYOTHER, values);
    }

    /**
     * Fetch records that have <code>blogparticipate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfBlogparticipate(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.BLOGPARTICIPATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>blogparticipate IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByBlogparticipate(String... values) {
        return fetch(Employers.EMPLOYERS.BLOGPARTICIPATE, values);
    }

    /**
     * Fetch records that have <code>notes BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfNotes(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.NOTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notes IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByNotes(String... values) {
        return fetch(Employers.EMPLOYERS.NOTES, values);
    }

    /**
     * Fetch records that have <code>datecreated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfDatecreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.DATECREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datecreated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByDatecreated(LocalDateTime... values) {
        return fetch(Employers.EMPLOYERS.DATECREATED, values);
    }

    /**
     * Fetch records that have <code>dateupdated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfDateupdated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.DATEUPDATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateupdated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByDateupdated(LocalDateTime... values) {
        return fetch(Employers.EMPLOYERS.DATEUPDATED, values);
    }

    /**
     * Fetch records that have <code>Createdby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Createdby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByCreatedby(String... values) {
        return fetch(Employers.EMPLOYERS.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>Updatedby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfUpdatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.UPDATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Updatedby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByUpdatedby(String... values) {
        return fetch(Employers.EMPLOYERS.UPDATEDBY, values);
    }

    /**
     * Fetch records that have <code>onlineSource BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfOnlinesource(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ONLINESOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>onlineSource IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByOnlinesource(String... values) {
        return fetch(Employers.EMPLOYERS.ONLINESOURCE, values);
    }

    /**
     * Fetch records that have <code>returnCustomer BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfReturncustomer(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.RETURNCUSTOMER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>returnCustomer IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByReturncustomer(String... values) {
        return fetch(Employers.EMPLOYERS.RETURNCUSTOMER, values);
    }

    /**
     * Fetch records that have <code>receiveUpdates BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfReceiveupdates(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.RECEIVEUPDATES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>receiveUpdates IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByReceiveupdates(String... values) {
        return fetch(Employers.EMPLOYERS.RECEIVEUPDATES, values);
    }

    /**
     * Fetch records that have <code>businessname BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfBusinessname(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.BUSINESSNAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>businessname IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByBusinessname(String... values) {
        return fetch(Employers.EMPLOYERS.BUSINESSNAME, values);
    }

    /**
     * Fetch records that have <code>licenseplate BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfLicenseplate(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.LICENSEPLATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>licenseplate IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByLicenseplate(String... values) {
        return fetch(Employers.EMPLOYERS.LICENSEPLATE, values);
    }

    /**
     * Fetch records that have <code>driverslicense BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfDriverslicense(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.DRIVERSLICENSE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>driverslicense IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByDriverslicense(String... values) {
        return fetch(Employers.EMPLOYERS.DRIVERSLICENSE, values);
    }

    /**
     * Fetch records that have <code>onlineSigninID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfOnlinesigninid(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ONLINESIGNINID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>onlineSigninID IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByOnlinesigninid(String... values) {
        return fetch(Employers.EMPLOYERS.ONLINESIGNINID, values);
    }

    /**
     * Fetch records that have <code>isOnlineProfileComplete BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfIsonlineprofilecomplete(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.ISONLINEPROFILECOMPLETE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>isOnlineProfileComplete IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByIsonlineprofilecomplete(String... values) {
        return fetch(Employers.EMPLOYERS.ISONLINEPROFILECOMPLETE, values);
    }

    /**
     * Fetch records that have <code>fax BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchRangeOfFax(String lowerInclusive, String upperInclusive) {
        return fetchRange(Employers.EMPLOYERS.FAX, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>fax IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Employers> fetchByFax(String... values) {
        return fetch(Employers.EMPLOYERS.FAX, values);
    }
}
