/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.daos;


import com.savagelearning.machete.core.tables.Transportproviders;
import com.savagelearning.machete.core.tables.records.TransportprovidersRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportprovidersDao extends DAOImpl<TransportprovidersRecord, com.savagelearning.machete.core.tables.pojos.Transportproviders, Integer> {

    /**
     * Create a new TransportprovidersDao without any configuration
     */
    public TransportprovidersDao() {
        super(Transportproviders.TRANSPORTPROVIDERS, com.savagelearning.machete.core.tables.pojos.Transportproviders.class);
    }

    /**
     * Create a new TransportprovidersDao with an attached configuration
     */
    public TransportprovidersDao(Configuration configuration) {
        super(Transportproviders.TRANSPORTPROVIDERS, com.savagelearning.machete.core.tables.pojos.Transportproviders.class, configuration);
    }

    @Override
    public Integer getId(com.savagelearning.machete.core.tables.pojos.Transportproviders object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchById(Integer... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.savagelearning.machete.core.tables.pojos.Transportproviders fetchOneById(Integer value) {
        return fetchOne(Transportproviders.TRANSPORTPROVIDERS.ID, value);
    }

    /**
     * Fetch records that have <code>key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByKey(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.KEY, values);
    }

    /**
     * Fetch records that have <code>text_EN BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfTextEn(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.TEXT_EN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>text_EN IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByTextEn(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.TEXT_EN, values);
    }

    /**
     * Fetch records that have <code>text_ES BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfTextEs(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.TEXT_ES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>text_ES IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByTextEs(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.TEXT_ES, values);
    }

    /**
     * Fetch records that have <code>defaultAttribute BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfDefaultattribute(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.DEFAULTATTRIBUTE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>defaultAttribute IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByDefaultattribute(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.DEFAULTATTRIBUTE, values);
    }

    /**
     * Fetch records that have <code>sortorder BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfSortorder(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.SORTORDER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>sortorder IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchBySortorder(Integer... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.SORTORDER, values);
    }

    /**
     * Fetch records that have <code>active BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfActive(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.ACTIVE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>active IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByActive(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.ACTIVE, values);
    }

    /**
     * Fetch records that have <code>datecreated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfDatecreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.DATECREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datecreated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByDatecreated(LocalDateTime... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.DATECREATED, values);
    }

    /**
     * Fetch records that have <code>dateupdated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfDateupdated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.DATEUPDATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateupdated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByDateupdated(LocalDateTime... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.DATEUPDATED, values);
    }

    /**
     * Fetch records that have <code>Createdby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Createdby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByCreatedby(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>Updatedby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchRangeOfUpdatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportproviders.TRANSPORTPROVIDERS.UPDATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Updatedby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportproviders> fetchByUpdatedby(String... values) {
        return fetch(Transportproviders.TRANSPORTPROVIDERS.UPDATEDBY, values);
    }
}
