/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.daos;


import com.savagelearning.machete.core.tables.Transportprovideravailabilities;
import com.savagelearning.machete.core.tables.records.TransportprovideravailabilitiesRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportprovideravailabilitiesDao extends DAOImpl<TransportprovideravailabilitiesRecord, com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities, Integer> {

    /**
     * Create a new TransportprovideravailabilitiesDao without any configuration
     */
    public TransportprovideravailabilitiesDao() {
        super(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES, com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities.class);
    }

    /**
     * Create a new TransportprovideravailabilitiesDao with an attached configuration
     */
    public TransportprovideravailabilitiesDao(Configuration configuration) {
        super(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES, com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities.class, configuration);
    }

    @Override
    public Integer getId(com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchById(Integer... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities fetchOneById(Integer value) {
        return fetchOne(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.ID, value);
    }

    /**
     * Fetch records that have <code>transportProviderID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfTransportproviderid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.TRANSPORTPROVIDERID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>transportProviderID IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByTransportproviderid(Integer... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.TRANSPORTPROVIDERID, values);
    }

    /**
     * Fetch records that have <code>key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>key IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByKey(String... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.KEY, values);
    }

    /**
     * Fetch records that have <code>lookupKey BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfLookupkey(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.LOOKUPKEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lookupKey IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByLookupkey(String... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.LOOKUPKEY, values);
    }

    /**
     * Fetch records that have <code>day BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfDay(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DAY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>day IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByDay(Integer... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DAY, values);
    }

    /**
     * Fetch records that have <code>available BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfAvailable(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.AVAILABLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>available IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByAvailable(String... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.AVAILABLE, values);
    }

    /**
     * Fetch records that have <code>datecreated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfDatecreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DATECREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datecreated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByDatecreated(LocalDateTime... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DATECREATED, values);
    }

    /**
     * Fetch records that have <code>dateupdated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfDateupdated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DATEUPDATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateupdated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByDateupdated(LocalDateTime... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.DATEUPDATED, values);
    }

    /**
     * Fetch records that have <code>Createdby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Createdby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByCreatedby(String... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>Updatedby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchRangeOfUpdatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.UPDATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Updatedby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportprovideravailabilities> fetchByUpdatedby(String... values) {
        return fetch(Transportprovideravailabilities.TRANSPORTPROVIDERAVAILABILITIES.UPDATEDBY, values);
    }
}
