/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.daos;


import com.savagelearning.machete.core.tables.Transportcostrules;
import com.savagelearning.machete.core.tables.records.TransportcostrulesRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportcostrulesDao extends DAOImpl<TransportcostrulesRecord, com.savagelearning.machete.core.tables.pojos.Transportcostrules, Integer> {

    /**
     * Create a new TransportcostrulesDao without any configuration
     */
    public TransportcostrulesDao() {
        super(Transportcostrules.TRANSPORTCOSTRULES, com.savagelearning.machete.core.tables.pojos.Transportcostrules.class);
    }

    /**
     * Create a new TransportcostrulesDao with an attached configuration
     */
    public TransportcostrulesDao(Configuration configuration) {
        super(Transportcostrules.TRANSPORTCOSTRULES, com.savagelearning.machete.core.tables.pojos.Transportcostrules.class, configuration);
    }

    @Override
    public Integer getId(com.savagelearning.machete.core.tables.pojos.Transportcostrules object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchById(Integer... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.savagelearning.machete.core.tables.pojos.Transportcostrules fetchOneById(Integer value) {
        return fetchOne(Transportcostrules.TRANSPORTCOSTRULES.ID, value);
    }

    /**
     * Fetch records that have <code>transportRuleID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfTransportruleid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.TRANSPORTRULEID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>transportRuleID IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByTransportruleid(Integer... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.TRANSPORTRULEID, values);
    }

    /**
     * Fetch records that have <code>minWorker BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfMinworker(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.MINWORKER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>minWorker IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByMinworker(Integer... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.MINWORKER, values);
    }

    /**
     * Fetch records that have <code>maxWorker BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfMaxworker(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.MAXWORKER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>maxWorker IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByMaxworker(Integer... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.MAXWORKER, values);
    }

    /**
     * Fetch records that have <code>cost BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfCost(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.COST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>cost IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByCost(Double... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.COST, values);
    }

    /**
     * Fetch records that have <code>datecreated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfDatecreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.DATECREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datecreated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByDatecreated(LocalDateTime... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.DATECREATED, values);
    }

    /**
     * Fetch records that have <code>dateupdated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfDateupdated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.DATEUPDATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateupdated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByDateupdated(LocalDateTime... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.DATEUPDATED, values);
    }

    /**
     * Fetch records that have <code>Createdby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Createdby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByCreatedby(String... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>Updatedby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchRangeOfUpdatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Transportcostrules.TRANSPORTCOSTRULES.UPDATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Updatedby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Transportcostrules> fetchByUpdatedby(String... values) {
        return fetch(Transportcostrules.TRANSPORTCOSTRULES.UPDATEDBY, values);
    }
}
