/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.daos;


import com.savagelearning.machete.core.tables.Workersignins;
import com.savagelearning.machete.core.tables.records.WorkersigninsRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkersigninsDao extends DAOImpl<WorkersigninsRecord, com.savagelearning.machete.core.tables.pojos.Workersignins, Integer> {

    /**
     * Create a new WorkersigninsDao without any configuration
     */
    public WorkersigninsDao() {
        super(Workersignins.WORKERSIGNINS, com.savagelearning.machete.core.tables.pojos.Workersignins.class);
    }

    /**
     * Create a new WorkersigninsDao with an attached configuration
     */
    public WorkersigninsDao(Configuration configuration) {
        super(Workersignins.WORKERSIGNINS, com.savagelearning.machete.core.tables.pojos.Workersignins.class, configuration);
    }

    @Override
    public Integer getId(com.savagelearning.machete.core.tables.pojos.Workersignins object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchById(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.savagelearning.machete.core.tables.pojos.Workersignins fetchOneById(Integer value) {
        return fetchOne(Workersignins.WORKERSIGNINS.ID, value);
    }

    /**
     * Fetch records that have <code>dwccardnum BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfDwccardnum(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.DWCCARDNUM, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dwccardnum IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByDwccardnum(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.DWCCARDNUM, values);
    }

    /**
     * Fetch records that have <code>WorkerID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfWorkerid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.WORKERID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>WorkerID IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByWorkerid(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.WORKERID, values);
    }

    /**
     * Fetch records that have <code>WorkAssignmentID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfWorkassignmentid(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.WORKASSIGNMENTID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>WorkAssignmentID IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByWorkassignmentid(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.WORKASSIGNMENTID, values);
    }

    /**
     * Fetch records that have <code>dateforsignin BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfDateforsignin(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.DATEFORSIGNIN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateforsignin IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByDateforsignin(LocalDateTime... values) {
        return fetch(Workersignins.WORKERSIGNINS.DATEFORSIGNIN, values);
    }

    /**
     * Fetch records that have <code>lottery_timestamp BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfLotteryTimestamp(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.LOTTERY_TIMESTAMP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lottery_timestamp IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByLotteryTimestamp(LocalDateTime... values) {
        return fetch(Workersignins.WORKERSIGNINS.LOTTERY_TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>datecreated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfDatecreated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.DATECREATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>datecreated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByDatecreated(LocalDateTime... values) {
        return fetch(Workersignins.WORKERSIGNINS.DATECREATED, values);
    }

    /**
     * Fetch records that have <code>dateupdated BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfDateupdated(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.DATEUPDATED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>dateupdated IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByDateupdated(LocalDateTime... values) {
        return fetch(Workersignins.WORKERSIGNINS.DATEUPDATED, values);
    }

    /**
     * Fetch records that have <code>Createdby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfCreatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.CREATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Createdby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByCreatedby(String... values) {
        return fetch(Workersignins.WORKERSIGNINS.CREATEDBY, values);
    }

    /**
     * Fetch records that have <code>Updatedby BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfUpdatedby(String lowerInclusive, String upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.UPDATEDBY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>Updatedby IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByUpdatedby(String... values) {
        return fetch(Workersignins.WORKERSIGNINS.UPDATEDBY, values);
    }

    /**
     * Fetch records that have <code>memberStatus BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfMemberstatus(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.MEMBERSTATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>memberStatus IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByMemberstatus(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.MEMBERSTATUS, values);
    }

    /**
     * Fetch records that have <code>lottery_sequence BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfLotterySequence(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.LOTTERY_SEQUENCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>lottery_sequence IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByLotterySequence(Integer... values) {
        return fetch(Workersignins.WORKERSIGNINS.LOTTERY_SEQUENCE, values);
    }

    /**
     * Fetch records that have <code>timeZoneOffset BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchRangeOfTimezoneoffset(Double lowerInclusive, Double upperInclusive) {
        return fetchRange(Workersignins.WORKERSIGNINS.TIMEZONEOFFSET, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timeZoneOffset IN (values)</code>
     */
    public List<com.savagelearning.machete.core.tables.pojos.Workersignins> fetchByTimezoneoffset(Double... values) {
        return fetch(Workersignins.WORKERSIGNINS.TIMEZONEOFFSET, values);
    }
}
