/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Configs;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigsRecord extends UpdatableRecordImpl<ConfigsRecord> implements Record10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Configs.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Configs.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Configs.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Configs.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.Configs.value</code>.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Configs.value</code>.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.Configs.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Configs.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.Configs.category</code>.
     */
    public void setCategory(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Configs.category</code>.
     */
    public String getCategory() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.Configs.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.Configs.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.Configs.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.Configs.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.Configs.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.Configs.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.Configs.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.Configs.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.Configs.publicConfig</code>.
     */
    public void setPublicconfig(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.Configs.publicConfig</code>.
     */
    public String getPublicconfig() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Configs.CONFIGS.ID;
    }

    @Override
    public Field<String> field2() {
        return Configs.CONFIGS.KEY;
    }

    @Override
    public Field<String> field3() {
        return Configs.CONFIGS.VALUE;
    }

    @Override
    public Field<String> field4() {
        return Configs.CONFIGS.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return Configs.CONFIGS.CATEGORY;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Configs.CONFIGS.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Configs.CONFIGS.DATEUPDATED;
    }

    @Override
    public Field<String> field8() {
        return Configs.CONFIGS.CREATEDBY;
    }

    @Override
    public Field<String> field9() {
        return Configs.CONFIGS.UPDATEDBY;
    }

    @Override
    public Field<String> field10() {
        return Configs.CONFIGS.PUBLICCONFIG;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getCategory();
    }

    @Override
    public LocalDateTime component6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component7() {
        return getDateupdated();
    }

    @Override
    public String component8() {
        return getCreatedby();
    }

    @Override
    public String component9() {
        return getUpdatedby();
    }

    @Override
    public String component10() {
        return getPublicconfig();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getCategory();
    }

    @Override
    public LocalDateTime value6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value7() {
        return getDateupdated();
    }

    @Override
    public String value8() {
        return getCreatedby();
    }

    @Override
    public String value9() {
        return getUpdatedby();
    }

    @Override
    public String value10() {
        return getPublicconfig();
    }

    @Override
    public ConfigsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ConfigsRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public ConfigsRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public ConfigsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ConfigsRecord value5(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ConfigsRecord value6(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public ConfigsRecord value7(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public ConfigsRecord value8(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public ConfigsRecord value9(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public ConfigsRecord value10(String value) {
        setPublicconfig(value);
        return this;
    }

    @Override
    public ConfigsRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigsRecord
     */
    public ConfigsRecord() {
        super(Configs.CONFIGS);
    }

    /**
     * Create a detached, initialised ConfigsRecord
     */
    public ConfigsRecord(Integer id, String key, String value, String description, String category, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, String publicconfig) {
        super(Configs.CONFIGS);

        setId(id);
        setKey(key);
        setValue(value);
        setDescription(description);
        setCategory(category);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setPublicconfig(publicconfig);
    }
}
