/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Emailworkorder;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmailworkorderRecord extends UpdatableRecordImpl<EmailworkorderRecord> implements Record7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.EmailWorkOrder.WorkOrder_ID</code>.
     */
    public void setWorkorderId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.WorkOrder_ID</code>.
     */
    public Integer getWorkorderId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.Email_ID</code>.
     */
    public void setEmailId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.Email_ID</code>.
     */
    public Integer getEmailId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.id</code>.
     */
    public void setId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.id</code>.
     */
    public Integer getId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.EmailWorkOrder.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.EmailWorkOrder.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Emailworkorder.EMAILWORKORDER.WORKORDER_ID;
    }

    @Override
    public Field<Integer> field2() {
        return Emailworkorder.EMAILWORKORDER.EMAIL_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Emailworkorder.EMAILWORKORDER.ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Emailworkorder.EMAILWORKORDER.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Emailworkorder.EMAILWORKORDER.DATEUPDATED;
    }

    @Override
    public Field<String> field6() {
        return Emailworkorder.EMAILWORKORDER.CREATEDBY;
    }

    @Override
    public Field<String> field7() {
        return Emailworkorder.EMAILWORKORDER.UPDATEDBY;
    }

    @Override
    public Integer component1() {
        return getWorkorderId();
    }

    @Override
    public Integer component2() {
        return getEmailId();
    }

    @Override
    public Integer component3() {
        return getId();
    }

    @Override
    public LocalDateTime component4() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component5() {
        return getDateupdated();
    }

    @Override
    public String component6() {
        return getCreatedby();
    }

    @Override
    public String component7() {
        return getUpdatedby();
    }

    @Override
    public Integer value1() {
        return getWorkorderId();
    }

    @Override
    public Integer value2() {
        return getEmailId();
    }

    @Override
    public Integer value3() {
        return getId();
    }

    @Override
    public LocalDateTime value4() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value5() {
        return getDateupdated();
    }

    @Override
    public String value6() {
        return getCreatedby();
    }

    @Override
    public String value7() {
        return getUpdatedby();
    }

    @Override
    public EmailworkorderRecord value1(Integer value) {
        setWorkorderId(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value2(Integer value) {
        setEmailId(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value3(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value4(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value5(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value6(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public EmailworkorderRecord value7(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public EmailworkorderRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmailworkorderRecord
     */
    public EmailworkorderRecord() {
        super(Emailworkorder.EMAILWORKORDER);
    }

    /**
     * Create a detached, initialised EmailworkorderRecord
     */
    public EmailworkorderRecord(Integer workorderId, Integer emailId, Integer id, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby) {
        super(Emailworkorder.EMAILWORKORDER);

        setWorkorderId(workorderId);
        setEmailId(emailId);
        setId(id);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
    }
}
