/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Events;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record12<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Events.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Events.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Events.PersonID</code>.
     */
    public void setPersonid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Events.PersonID</code>.
     */
    public Integer getPersonid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.Events.eventType</code>.
     */
    public void setEventtype(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Events.eventType</code>.
     */
    public Integer getEventtype() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.Events.dateFrom</code>.
     */
    public void setDatefrom(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Events.dateFrom</code>.
     */
    public LocalDateTime getDatefrom() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.Events.dateTo</code>.
     */
    public void setDateto(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Events.dateTo</code>.
     */
    public LocalDateTime getDateto() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.Events.notes</code>.
     */
    public void setNotes(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.Events.notes</code>.
     */
    public String getNotes() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.Events.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.Events.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.Events.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.Events.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.Events.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.Events.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.Events.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.Events.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.Events.eventTypeEN</code>.
     */
    public void setEventtypeen(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.Events.eventTypeEN</code>.
     */
    public String getEventtypeen() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.Events.eventTypeES</code>.
     */
    public void setEventtypees(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.Events.eventTypeES</code>.
     */
    public String getEventtypees() {
        return (String) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Events.EVENTS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Events.EVENTS.PERSONID;
    }

    @Override
    public Field<Integer> field3() {
        return Events.EVENTS.EVENTTYPE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Events.EVENTS.DATEFROM;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Events.EVENTS.DATETO;
    }

    @Override
    public Field<String> field6() {
        return Events.EVENTS.NOTES;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Events.EVENTS.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Events.EVENTS.DATEUPDATED;
    }

    @Override
    public Field<String> field9() {
        return Events.EVENTS.CREATEDBY;
    }

    @Override
    public Field<String> field10() {
        return Events.EVENTS.UPDATEDBY;
    }

    @Override
    public Field<String> field11() {
        return Events.EVENTS.EVENTTYPEEN;
    }

    @Override
    public Field<String> field12() {
        return Events.EVENTS.EVENTTYPEES;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPersonid();
    }

    @Override
    public Integer component3() {
        return getEventtype();
    }

    @Override
    public LocalDateTime component4() {
        return getDatefrom();
    }

    @Override
    public LocalDateTime component5() {
        return getDateto();
    }

    @Override
    public String component6() {
        return getNotes();
    }

    @Override
    public LocalDateTime component7() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component8() {
        return getDateupdated();
    }

    @Override
    public String component9() {
        return getCreatedby();
    }

    @Override
    public String component10() {
        return getUpdatedby();
    }

    @Override
    public String component11() {
        return getEventtypeen();
    }

    @Override
    public String component12() {
        return getEventtypees();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPersonid();
    }

    @Override
    public Integer value3() {
        return getEventtype();
    }

    @Override
    public LocalDateTime value4() {
        return getDatefrom();
    }

    @Override
    public LocalDateTime value5() {
        return getDateto();
    }

    @Override
    public String value6() {
        return getNotes();
    }

    @Override
    public LocalDateTime value7() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value8() {
        return getDateupdated();
    }

    @Override
    public String value9() {
        return getCreatedby();
    }

    @Override
    public String value10() {
        return getUpdatedby();
    }

    @Override
    public String value11() {
        return getEventtypeen();
    }

    @Override
    public String value12() {
        return getEventtypees();
    }

    @Override
    public EventsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public EventsRecord value2(Integer value) {
        setPersonid(value);
        return this;
    }

    @Override
    public EventsRecord value3(Integer value) {
        setEventtype(value);
        return this;
    }

    @Override
    public EventsRecord value4(LocalDateTime value) {
        setDatefrom(value);
        return this;
    }

    @Override
    public EventsRecord value5(LocalDateTime value) {
        setDateto(value);
        return this;
    }

    @Override
    public EventsRecord value6(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public EventsRecord value7(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public EventsRecord value8(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public EventsRecord value9(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public EventsRecord value10(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public EventsRecord value11(String value) {
        setEventtypeen(value);
        return this;
    }

    @Override
    public EventsRecord value12(String value) {
        setEventtypees(value);
        return this;
    }

    @Override
    public EventsRecord values(Integer value1, Integer value2, Integer value3, LocalDateTime value4, LocalDateTime value5, String value6, LocalDateTime value7, LocalDateTime value8, String value9, String value10, String value11, String value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Integer id, Integer personid, Integer eventtype, LocalDateTime datefrom, LocalDateTime dateto, String notes, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, String eventtypeen, String eventtypees) {
        super(Events.EVENTS);

        setId(id);
        setPersonid(personid);
        setEventtype(eventtype);
        setDatefrom(datefrom);
        setDateto(dateto);
        setNotes(notes);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setEventtypeen(eventtypeen);
        setEventtypees(eventtypees);
    }
}
