/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Joineventimage;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JoineventimageRecord extends UpdatableRecordImpl<JoineventimageRecord> implements Record7<Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.JoinEventImage.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.JoinEventImage.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.JoinEventImage.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.JoinEventImage.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.JoinEventImage.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.JoinEventImage.EventID</code>.
     */
    public void setEventid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.EventID</code>.
     */
    public Integer getEventid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.JoinEventImage.ImageID</code>.
     */
    public void setImageid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.JoinEventImage.ImageID</code>.
     */
    public Integer getImageid() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, LocalDateTime, LocalDateTime, String, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Joineventimage.JOINEVENTIMAGE.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Joineventimage.JOINEVENTIMAGE.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Joineventimage.JOINEVENTIMAGE.DATEUPDATED;
    }

    @Override
    public Field<String> field4() {
        return Joineventimage.JOINEVENTIMAGE.CREATEDBY;
    }

    @Override
    public Field<String> field5() {
        return Joineventimage.JOINEVENTIMAGE.UPDATEDBY;
    }

    @Override
    public Field<Integer> field6() {
        return Joineventimage.JOINEVENTIMAGE.EVENTID;
    }

    @Override
    public Field<Integer> field7() {
        return Joineventimage.JOINEVENTIMAGE.IMAGEID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component3() {
        return getDateupdated();
    }

    @Override
    public String component4() {
        return getCreatedby();
    }

    @Override
    public String component5() {
        return getUpdatedby();
    }

    @Override
    public Integer component6() {
        return getEventid();
    }

    @Override
    public Integer component7() {
        return getImageid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value3() {
        return getDateupdated();
    }

    @Override
    public String value4() {
        return getCreatedby();
    }

    @Override
    public String value5() {
        return getUpdatedby();
    }

    @Override
    public Integer value6() {
        return getEventid();
    }

    @Override
    public Integer value7() {
        return getImageid();
    }

    @Override
    public JoineventimageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public JoineventimageRecord value2(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public JoineventimageRecord value3(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public JoineventimageRecord value4(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public JoineventimageRecord value5(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public JoineventimageRecord value6(Integer value) {
        setEventid(value);
        return this;
    }

    @Override
    public JoineventimageRecord value7(Integer value) {
        setImageid(value);
        return this;
    }

    @Override
    public JoineventimageRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JoineventimageRecord
     */
    public JoineventimageRecord() {
        super(Joineventimage.JOINEVENTIMAGE);
    }

    /**
     * Create a detached, initialised JoineventimageRecord
     */
    public JoineventimageRecord(Integer id, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, Integer eventid, Integer imageid) {
        super(Joineventimage.JOINEVENTIMAGE);

        setId(id);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setEventid(eventid);
        setImageid(imageid);
    }
}
