/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Reportdefinitions;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportdefinitionsRecord extends UpdatableRecordImpl<ReportdefinitionsRecord> implements Record14<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ReportDefinitions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ReportDefinitions.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.ReportDefinitions.commonName</code>.
     */
    public void setCommonname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.commonName</code>.
     */
    public String getCommonname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ReportDefinitions.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ReportDefinitions.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ReportDefinitions.sqlquery</code>.
     */
    public void setSqlquery(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.sqlquery</code>.
     */
    public String getSqlquery() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.ReportDefinitions.category</code>.
     */
    public void setCategory(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.category</code>.
     */
    public String getCategory() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.ReportDefinitions.subcategory</code>.
     */
    public void setSubcategory(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.subcategory</code>.
     */
    public String getSubcategory() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.ReportDefinitions.inputsJson</code>.
     */
    public void setInputsjson(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.inputsJson</code>.
     */
    public String getInputsjson() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.ReportDefinitions.columnsJson</code>.
     */
    public void setColumnsjson(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.columnsJson</code>.
     */
    public String getColumnsjson() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.ReportDefinitions.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.ReportDefinitions.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.ReportDefinitions.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.ReportDefinitions.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.ReportDefinitions.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Reportdefinitions.REPORTDEFINITIONS.ID;
    }

    @Override
    public Field<String> field2() {
        return Reportdefinitions.REPORTDEFINITIONS.NAME;
    }

    @Override
    public Field<String> field3() {
        return Reportdefinitions.REPORTDEFINITIONS.COMMONNAME;
    }

    @Override
    public Field<String> field4() {
        return Reportdefinitions.REPORTDEFINITIONS.TITLE;
    }

    @Override
    public Field<String> field5() {
        return Reportdefinitions.REPORTDEFINITIONS.DESCRIPTION;
    }

    @Override
    public Field<String> field6() {
        return Reportdefinitions.REPORTDEFINITIONS.SQLQUERY;
    }

    @Override
    public Field<String> field7() {
        return Reportdefinitions.REPORTDEFINITIONS.CATEGORY;
    }

    @Override
    public Field<String> field8() {
        return Reportdefinitions.REPORTDEFINITIONS.SUBCATEGORY;
    }

    @Override
    public Field<String> field9() {
        return Reportdefinitions.REPORTDEFINITIONS.INPUTSJSON;
    }

    @Override
    public Field<String> field10() {
        return Reportdefinitions.REPORTDEFINITIONS.COLUMNSJSON;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Reportdefinitions.REPORTDEFINITIONS.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Reportdefinitions.REPORTDEFINITIONS.DATEUPDATED;
    }

    @Override
    public Field<String> field13() {
        return Reportdefinitions.REPORTDEFINITIONS.CREATEDBY;
    }

    @Override
    public Field<String> field14() {
        return Reportdefinitions.REPORTDEFINITIONS.UPDATEDBY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getCommonname();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public String component6() {
        return getSqlquery();
    }

    @Override
    public String component7() {
        return getCategory();
    }

    @Override
    public String component8() {
        return getSubcategory();
    }

    @Override
    public String component9() {
        return getInputsjson();
    }

    @Override
    public String component10() {
        return getColumnsjson();
    }

    @Override
    public LocalDateTime component11() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component12() {
        return getDateupdated();
    }

    @Override
    public String component13() {
        return getCreatedby();
    }

    @Override
    public String component14() {
        return getUpdatedby();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getCommonname();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public String value6() {
        return getSqlquery();
    }

    @Override
    public String value7() {
        return getCategory();
    }

    @Override
    public String value8() {
        return getSubcategory();
    }

    @Override
    public String value9() {
        return getInputsjson();
    }

    @Override
    public String value10() {
        return getColumnsjson();
    }

    @Override
    public LocalDateTime value11() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value12() {
        return getDateupdated();
    }

    @Override
    public String value13() {
        return getCreatedby();
    }

    @Override
    public String value14() {
        return getUpdatedby();
    }

    @Override
    public ReportdefinitionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value3(String value) {
        setCommonname(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value6(String value) {
        setSqlquery(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value7(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value8(String value) {
        setSubcategory(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value9(String value) {
        setInputsjson(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value10(String value) {
        setColumnsjson(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value11(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value12(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value13(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord value14(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public ReportdefinitionsRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportdefinitionsRecord
     */
    public ReportdefinitionsRecord() {
        super(Reportdefinitions.REPORTDEFINITIONS);
    }

    /**
     * Create a detached, initialised ReportdefinitionsRecord
     */
    public ReportdefinitionsRecord(Integer id, String name, String commonname, String title, String description, String sqlquery, String category, String subcategory, String inputsjson, String columnsjson, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby) {
        super(Reportdefinitions.REPORTDEFINITIONS);

        setId(id);
        setName(name);
        setCommonname(commonname);
        setTitle(title);
        setDescription(description);
        setSqlquery(sqlquery);
        setCategory(category);
        setSubcategory(subcategory);
        setInputsjson(inputsjson);
        setColumnsjson(columnsjson);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
    }
}
