/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Schedulerules;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchedulerulesRecord extends UpdatableRecordImpl<SchedulerulesRecord> implements Record9<Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ScheduleRules.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.ScheduleRules.day</code>.
     */
    public void setDay(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.day</code>.
     */
    public Integer getDay() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.ScheduleRules.leadHours</code>.
     */
    public void setLeadhours(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.leadHours</code>.
     */
    public Integer getLeadhours() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.ScheduleRules.minStartMin</code>.
     */
    public void setMinstartmin(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.minStartMin</code>.
     */
    public Integer getMinstartmin() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.ScheduleRules.maxEndMin</code>.
     */
    public void setMaxendmin(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.maxEndMin</code>.
     */
    public Integer getMaxendmin() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.ScheduleRules.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.ScheduleRules.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.ScheduleRules.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.ScheduleRules.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.ScheduleRules.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Schedulerules.SCHEDULERULES.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Schedulerules.SCHEDULERULES.DAY;
    }

    @Override
    public Field<Integer> field3() {
        return Schedulerules.SCHEDULERULES.LEADHOURS;
    }

    @Override
    public Field<Integer> field4() {
        return Schedulerules.SCHEDULERULES.MINSTARTMIN;
    }

    @Override
    public Field<Integer> field5() {
        return Schedulerules.SCHEDULERULES.MAXENDMIN;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Schedulerules.SCHEDULERULES.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Schedulerules.SCHEDULERULES.DATEUPDATED;
    }

    @Override
    public Field<String> field8() {
        return Schedulerules.SCHEDULERULES.CREATEDBY;
    }

    @Override
    public Field<String> field9() {
        return Schedulerules.SCHEDULERULES.UPDATEDBY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDay();
    }

    @Override
    public Integer component3() {
        return getLeadhours();
    }

    @Override
    public Integer component4() {
        return getMinstartmin();
    }

    @Override
    public Integer component5() {
        return getMaxendmin();
    }

    @Override
    public LocalDateTime component6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component7() {
        return getDateupdated();
    }

    @Override
    public String component8() {
        return getCreatedby();
    }

    @Override
    public String component9() {
        return getUpdatedby();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDay();
    }

    @Override
    public Integer value3() {
        return getLeadhours();
    }

    @Override
    public Integer value4() {
        return getMinstartmin();
    }

    @Override
    public Integer value5() {
        return getMaxendmin();
    }

    @Override
    public LocalDateTime value6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value7() {
        return getDateupdated();
    }

    @Override
    public String value8() {
        return getCreatedby();
    }

    @Override
    public String value9() {
        return getUpdatedby();
    }

    @Override
    public SchedulerulesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value2(Integer value) {
        setDay(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value3(Integer value) {
        setLeadhours(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value4(Integer value) {
        setMinstartmin(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value5(Integer value) {
        setMaxendmin(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value6(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value7(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value8(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public SchedulerulesRecord value9(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public SchedulerulesRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, LocalDateTime value6, LocalDateTime value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SchedulerulesRecord
     */
    public SchedulerulesRecord() {
        super(Schedulerules.SCHEDULERULES);
    }

    /**
     * Create a detached, initialised SchedulerulesRecord
     */
    public SchedulerulesRecord(Integer id, Integer day, Integer leadhours, Integer minstartmin, Integer maxendmin, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby) {
        super(Schedulerules.SCHEDULERULES);

        setId(id);
        setDay(day);
        setLeadhours(leadhours);
        setMinstartmin(minstartmin);
        setMaxendmin(maxendmin);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
    }
}
