/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Transportrules;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportrulesRecord extends UpdatableRecordImpl<TransportrulesRecord> implements Record9<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.TransportRules.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.TransportRules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.TransportRules.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.TransportRules.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.TransportRules.lookupKey</code>.
     */
    public void setLookupkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.TransportRules.lookupKey</code>.
     */
    public String getLookupkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.TransportRules.zoneLabel</code>.
     */
    public void setZonelabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.TransportRules.zoneLabel</code>.
     */
    public String getZonelabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.TransportRules.zipcodes</code>.
     */
    public void setZipcodes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.TransportRules.zipcodes</code>.
     */
    public String getZipcodes() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.TransportRules.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.TransportRules.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.TransportRules.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.TransportRules.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.TransportRules.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.TransportRules.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.TransportRules.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.TransportRules.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, String, String, LocalDateTime, LocalDateTime, String, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Transportrules.TRANSPORTRULES.ID;
    }

    @Override
    public Field<String> field2() {
        return Transportrules.TRANSPORTRULES.KEY;
    }

    @Override
    public Field<String> field3() {
        return Transportrules.TRANSPORTRULES.LOOKUPKEY;
    }

    @Override
    public Field<String> field4() {
        return Transportrules.TRANSPORTRULES.ZONELABEL;
    }

    @Override
    public Field<String> field5() {
        return Transportrules.TRANSPORTRULES.ZIPCODES;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Transportrules.TRANSPORTRULES.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Transportrules.TRANSPORTRULES.DATEUPDATED;
    }

    @Override
    public Field<String> field8() {
        return Transportrules.TRANSPORTRULES.CREATEDBY;
    }

    @Override
    public Field<String> field9() {
        return Transportrules.TRANSPORTRULES.UPDATEDBY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getLookupkey();
    }

    @Override
    public String component4() {
        return getZonelabel();
    }

    @Override
    public String component5() {
        return getZipcodes();
    }

    @Override
    public LocalDateTime component6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component7() {
        return getDateupdated();
    }

    @Override
    public String component8() {
        return getCreatedby();
    }

    @Override
    public String component9() {
        return getUpdatedby();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getLookupkey();
    }

    @Override
    public String value4() {
        return getZonelabel();
    }

    @Override
    public String value5() {
        return getZipcodes();
    }

    @Override
    public LocalDateTime value6() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value7() {
        return getDateupdated();
    }

    @Override
    public String value8() {
        return getCreatedby();
    }

    @Override
    public String value9() {
        return getUpdatedby();
    }

    @Override
    public TransportrulesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TransportrulesRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public TransportrulesRecord value3(String value) {
        setLookupkey(value);
        return this;
    }

    @Override
    public TransportrulesRecord value4(String value) {
        setZonelabel(value);
        return this;
    }

    @Override
    public TransportrulesRecord value5(String value) {
        setZipcodes(value);
        return this;
    }

    @Override
    public TransportrulesRecord value6(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public TransportrulesRecord value7(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public TransportrulesRecord value8(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public TransportrulesRecord value9(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public TransportrulesRecord values(Integer value1, String value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7, String value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransportrulesRecord
     */
    public TransportrulesRecord() {
        super(Transportrules.TRANSPORTRULES);
    }

    /**
     * Create a detached, initialised TransportrulesRecord
     */
    public TransportrulesRecord(Integer id, String key, String lookupkey, String zonelabel, String zipcodes, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby) {
        super(Transportrules.TRANSPORTRULES);

        setId(id);
        setKey(key);
        setLookupkey(lookupkey);
        setZonelabel(zonelabel);
        setZipcodes(zipcodes);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
    }
}
