/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Workersignins;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkersigninsRecord extends UpdatableRecordImpl<WorkersigninsRecord> implements Record13<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.WorkerSignins.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.WorkerSignins.dwccardnum</code>.
     */
    public void setDwccardnum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.dwccardnum</code>.
     */
    public Integer getDwccardnum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.WorkerSignins.WorkerID</code>.
     */
    public void setWorkerid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.WorkerID</code>.
     */
    public Integer getWorkerid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.WorkerSignins.WorkAssignmentID</code>.
     */
    public void setWorkassignmentid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.WorkAssignmentID</code>.
     */
    public Integer getWorkassignmentid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.WorkerSignins.dateforsignin</code>.
     */
    public void setDateforsignin(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.dateforsignin</code>.
     */
    public LocalDateTime getDateforsignin() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.WorkerSignins.lottery_timestamp</code>.
     */
    public void setLotteryTimestamp(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.lottery_timestamp</code>.
     */
    public LocalDateTime getLotteryTimestamp() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.WorkerSignins.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.WorkerSignins.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.WorkerSignins.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.WorkerSignins.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.WorkerSignins.memberStatus</code>.
     */
    public void setMemberstatus(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.memberStatus</code>.
     */
    public Integer getMemberstatus() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.WorkerSignins.lottery_sequence</code>.
     */
    public void setLotterySequence(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.lottery_sequence</code>.
     */
    public Integer getLotterySequence() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.WorkerSignins.timeZoneOffset</code>.
     */
    public void setTimezoneoffset(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.WorkerSignins.timeZoneOffset</code>.
     */
    public Double getTimezoneoffset() {
        return (Double) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Double> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, Integer, Integer, Integer, LocalDateTime, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Integer, Double> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Workersignins.WORKERSIGNINS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Workersignins.WORKERSIGNINS.DWCCARDNUM;
    }

    @Override
    public Field<Integer> field3() {
        return Workersignins.WORKERSIGNINS.WORKERID;
    }

    @Override
    public Field<Integer> field4() {
        return Workersignins.WORKERSIGNINS.WORKASSIGNMENTID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Workersignins.WORKERSIGNINS.DATEFORSIGNIN;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Workersignins.WORKERSIGNINS.LOTTERY_TIMESTAMP;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Workersignins.WORKERSIGNINS.DATECREATED;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Workersignins.WORKERSIGNINS.DATEUPDATED;
    }

    @Override
    public Field<String> field9() {
        return Workersignins.WORKERSIGNINS.CREATEDBY;
    }

    @Override
    public Field<String> field10() {
        return Workersignins.WORKERSIGNINS.UPDATEDBY;
    }

    @Override
    public Field<Integer> field11() {
        return Workersignins.WORKERSIGNINS.MEMBERSTATUS;
    }

    @Override
    public Field<Integer> field12() {
        return Workersignins.WORKERSIGNINS.LOTTERY_SEQUENCE;
    }

    @Override
    public Field<Double> field13() {
        return Workersignins.WORKERSIGNINS.TIMEZONEOFFSET;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getDwccardnum();
    }

    @Override
    public Integer component3() {
        return getWorkerid();
    }

    @Override
    public Integer component4() {
        return getWorkassignmentid();
    }

    @Override
    public LocalDateTime component5() {
        return getDateforsignin();
    }

    @Override
    public LocalDateTime component6() {
        return getLotteryTimestamp();
    }

    @Override
    public LocalDateTime component7() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime component8() {
        return getDateupdated();
    }

    @Override
    public String component9() {
        return getCreatedby();
    }

    @Override
    public String component10() {
        return getUpdatedby();
    }

    @Override
    public Integer component11() {
        return getMemberstatus();
    }

    @Override
    public Integer component12() {
        return getLotterySequence();
    }

    @Override
    public Double component13() {
        return getTimezoneoffset();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getDwccardnum();
    }

    @Override
    public Integer value3() {
        return getWorkerid();
    }

    @Override
    public Integer value4() {
        return getWorkassignmentid();
    }

    @Override
    public LocalDateTime value5() {
        return getDateforsignin();
    }

    @Override
    public LocalDateTime value6() {
        return getLotteryTimestamp();
    }

    @Override
    public LocalDateTime value7() {
        return getDatecreated();
    }

    @Override
    public LocalDateTime value8() {
        return getDateupdated();
    }

    @Override
    public String value9() {
        return getCreatedby();
    }

    @Override
    public String value10() {
        return getUpdatedby();
    }

    @Override
    public Integer value11() {
        return getMemberstatus();
    }

    @Override
    public Integer value12() {
        return getLotterySequence();
    }

    @Override
    public Double value13() {
        return getTimezoneoffset();
    }

    @Override
    public WorkersigninsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value2(Integer value) {
        setDwccardnum(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value3(Integer value) {
        setWorkerid(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value4(Integer value) {
        setWorkassignmentid(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value5(LocalDateTime value) {
        setDateforsignin(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value6(LocalDateTime value) {
        setLotteryTimestamp(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value7(LocalDateTime value) {
        setDatecreated(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value8(LocalDateTime value) {
        setDateupdated(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value9(String value) {
        setCreatedby(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value10(String value) {
        setUpdatedby(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value11(Integer value) {
        setMemberstatus(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value12(Integer value) {
        setLotterySequence(value);
        return this;
    }

    @Override
    public WorkersigninsRecord value13(Double value) {
        setTimezoneoffset(value);
        return this;
    }

    @Override
    public WorkersigninsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, LocalDateTime value5, LocalDateTime value6, LocalDateTime value7, LocalDateTime value8, String value9, String value10, Integer value11, Integer value12, Double value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkersigninsRecord
     */
    public WorkersigninsRecord() {
        super(Workersignins.WORKERSIGNINS);
    }

    /**
     * Create a detached, initialised WorkersigninsRecord
     */
    public WorkersigninsRecord(Integer id, Integer dwccardnum, Integer workerid, Integer workassignmentid, LocalDateTime dateforsignin, LocalDateTime lotteryTimestamp, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, Integer memberstatus, Integer lotterySequence, Double timezoneoffset) {
        super(Workersignins.WORKERSIGNINS);

        setId(id);
        setDwccardnum(dwccardnum);
        setWorkerid(workerid);
        setWorkassignmentid(workassignmentid);
        setDateforsignin(dateforsignin);
        setLotteryTimestamp(lotteryTimestamp);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setMemberstatus(memberstatus);
        setLotterySequence(lotterySequence);
        setTimezoneoffset(timezoneoffset);
    }
}
