/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Workassignments;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkassignmentsRecord extends UpdatableRecordImpl<WorkassignmentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.WorkAssignments.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.WorkAssignments.workerAssignedID</code>.
     */
    public void setWorkerassignedid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.workerAssignedID</code>.
     */
    public Integer getWorkerassignedid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.WorkAssignments.workOrderID</code>.
     */
    public void setWorkorderid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.workOrderID</code>.
     */
    public Integer getWorkorderid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.WorkAssignments.workerSigninID</code>.
     */
    public void setWorkersigninid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.workerSigninID</code>.
     */
    public Integer getWorkersigninid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.WorkAssignments.active</code>.
     */
    public void setActive(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.active</code>.
     */
    public String getActive() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.WorkAssignments.pseudoID</code>.
     */
    public void setPseudoid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.pseudoID</code>.
     */
    public Integer getPseudoid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.WorkAssignments.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.WorkAssignments.englishLevelID</code>.
     */
    public void setEnglishlevelid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.englishLevelID</code>.
     */
    public Integer getEnglishlevelid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.WorkAssignments.skillID</code>.
     */
    public void setSkillid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.skillID</code>.
     */
    public Integer getSkillid() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.WorkAssignments.hourlyWage</code>.
     */
    public void setHourlywage(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.hourlyWage</code>.
     */
    public Double getHourlywage() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>public.WorkAssignments.hours</code>.
     */
    public void setHours(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.hours</code>.
     */
    public Double getHours() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>public.WorkAssignments.hourRange</code>.
     */
    public void setHourrange(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.hourRange</code>.
     */
    public Integer getHourrange() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.WorkAssignments.days</code>.
     */
    public void setDays(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.days</code>.
     */
    public Integer getDays() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.WorkAssignments.qualityOfWork</code>.
     */
    public void setQualityofwork(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.qualityOfWork</code>.
     */
    public Integer getQualityofwork() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.WorkAssignments.followDirections</code>.
     */
    public void setFollowdirections(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.followDirections</code>.
     */
    public Integer getFollowdirections() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.WorkAssignments.attitude</code>.
     */
    public void setAttitude(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.attitude</code>.
     */
    public Integer getAttitude() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.WorkAssignments.reliability</code>.
     */
    public void setReliability(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.reliability</code>.
     */
    public Integer getReliability() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.WorkAssignments.transportProgram</code>.
     */
    public void setTransportprogram(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.transportProgram</code>.
     */
    public Integer getTransportprogram() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.WorkAssignments.comments</code>.
     */
    public void setComments(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.comments</code>.
     */
    public String getComments() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.WorkAssignments.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.WorkAssignments.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>public.WorkAssignments.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.WorkAssignments.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.WorkAssignments.surcharge</code>.
     */
    public void setSurcharge(Double value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.surcharge</code>.
     */
    public Double getSurcharge() {
        return (Double) get(23);
    }

    /**
     * Setter for <code>public.WorkAssignments.workerRating</code>.
     */
    public void setWorkerrating(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.workerRating</code>.
     */
    public Integer getWorkerrating() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.WorkAssignments.workerRatingComments</code>.
     */
    public void setWorkerratingcomments(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.workerRatingComments</code>.
     */
    public String getWorkerratingcomments() {
        return (String) get(25);
    }

    /**
     * Setter for <code>public.WorkAssignments.weightLifted</code>.
     */
    public void setWeightlifted(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.weightLifted</code>.
     */
    public String getWeightlifted() {
        return (String) get(26);
    }

    /**
     * Setter for <code>public.WorkAssignments.skillEN</code>.
     */
    public void setSkillen(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.skillEN</code>.
     */
    public String getSkillen() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.WorkAssignments.skillES</code>.
     */
    public void setSkilles(String value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.skillES</code>.
     */
    public String getSkilles() {
        return (String) get(28);
    }

    /**
     * Setter for <code>public.WorkAssignments.fullWAID</code>.
     */
    public void setFullwaid(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.fullWAID</code>.
     */
    public String getFullwaid() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.WorkAssignments.minEarnings</code>.
     */
    public void setMinearnings(Double value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.minEarnings</code>.
     */
    public Double getMinearnings() {
        return (Double) get(30);
    }

    /**
     * Setter for <code>public.WorkAssignments.maxEarnings</code>.
     */
    public void setMaxearnings(Double value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.maxEarnings</code>.
     */
    public Double getMaxearnings() {
        return (Double) get(31);
    }

    /**
     * Setter for <code>public.WorkAssignments.transportCost</code>.
     */
    public void setTransportcost(Double value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.WorkAssignments.transportCost</code>.
     */
    public Double getTransportcost() {
        return (Double) get(32);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkassignmentsRecord
     */
    public WorkassignmentsRecord() {
        super(Workassignments.WORKASSIGNMENTS);
    }

    /**
     * Create a detached, initialised WorkassignmentsRecord
     */
    public WorkassignmentsRecord(Integer id, Integer workerassignedid, Integer workorderid, Integer workersigninid, String active, Integer pseudoid, String description, Integer englishlevelid, Integer skillid, Double hourlywage, Double hours, Integer hourrange, Integer days, Integer qualityofwork, Integer followdirections, Integer attitude, Integer reliability, Integer transportprogram, String comments, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, Double surcharge, Integer workerrating, String workerratingcomments, String weightlifted, String skillen, String skilles, String fullwaid, Double minearnings, Double maxearnings, Double transportcost) {
        super(Workassignments.WORKASSIGNMENTS);

        setId(id);
        setWorkerassignedid(workerassignedid);
        setWorkorderid(workorderid);
        setWorkersigninid(workersigninid);
        setActive(active);
        setPseudoid(pseudoid);
        setDescription(description);
        setEnglishlevelid(englishlevelid);
        setSkillid(skillid);
        setHourlywage(hourlywage);
        setHours(hours);
        setHourrange(hourrange);
        setDays(days);
        setQualityofwork(qualityofwork);
        setFollowdirections(followdirections);
        setAttitude(attitude);
        setReliability(reliability);
        setTransportprogram(transportprogram);
        setComments(comments);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setSurcharge(surcharge);
        setWorkerrating(workerrating);
        setWorkerratingcomments(workerratingcomments);
        setWeightlifted(weightlifted);
        setSkillen(skillen);
        setSkilles(skilles);
        setFullwaid(fullwaid);
        setMinearnings(minearnings);
        setMaxearnings(maxearnings);
        setTransportcost(transportcost);
    }
}
