/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables.records;


import com.savagelearning.machete.core.tables.Workers;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkersRecord extends UpdatableRecordImpl<WorkersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.Workers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.Workers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.Workers.typeOfWorkID</code>.
     */
    public void setTypeofworkid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.Workers.typeOfWorkID</code>.
     */
    public Integer getTypeofworkid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.Workers.dateOfMembership</code>.
     */
    public void setDateofmembership(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.Workers.dateOfMembership</code>.
     */
    public LocalDateTime getDateofmembership() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.Workers.dateOfBirth</code>.
     */
    public void setDateofbirth(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.Workers.dateOfBirth</code>.
     */
    public LocalDateTime getDateofbirth() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.Workers.memberStatus</code>.
     */
    public void setMemberstatus(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.Workers.memberStatus</code>.
     */
    public Integer getMemberstatus() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.Workers.memberReactivateDate</code>.
     */
    public void setMemberreactivatedate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.Workers.memberReactivateDate</code>.
     */
    public LocalDateTime getMemberreactivatedate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.Workers.active</code>.
     */
    public void setActive(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.Workers.active</code>.
     */
    public String getActive() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.Workers.RaceID</code>.
     */
    public void setRaceid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.Workers.RaceID</code>.
     */
    public Integer getRaceid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.Workers.raceother</code>.
     */
    public void setRaceother(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.Workers.raceother</code>.
     */
    public String getRaceother() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.Workers.height</code>.
     */
    public void setHeight(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.Workers.height</code>.
     */
    public String getHeight() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.Workers.weight</code>.
     */
    public void setWeight(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.Workers.weight</code>.
     */
    public String getWeight() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.Workers.englishlevelID</code>.
     */
    public void setEnglishlevelid(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.Workers.englishlevelID</code>.
     */
    public Integer getEnglishlevelid() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.Workers.recentarrival</code>.
     */
    public void setRecentarrival(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.Workers.recentarrival</code>.
     */
    public String getRecentarrival() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.Workers.dateinUSA</code>.
     */
    public void setDateinusa(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.Workers.dateinUSA</code>.
     */
    public LocalDateTime getDateinusa() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.Workers.dateinseattle</code>.
     */
    public void setDateinseattle(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.Workers.dateinseattle</code>.
     */
    public LocalDateTime getDateinseattle() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.Workers.disabled</code>.
     */
    public void setDisabled(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.Workers.disabled</code>.
     */
    public String getDisabled() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.Workers.disabilitydesc</code>.
     */
    public void setDisabilitydesc(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.Workers.disabilitydesc</code>.
     */
    public String getDisabilitydesc() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.Workers.maritalstatus</code>.
     */
    public void setMaritalstatus(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.Workers.maritalstatus</code>.
     */
    public Integer getMaritalstatus() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.Workers.livewithchildren</code>.
     */
    public void setLivewithchildren(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.Workers.livewithchildren</code>.
     */
    public String getLivewithchildren() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.Workers.numofchildren</code>.
     */
    public void setNumofchildren(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.Workers.numofchildren</code>.
     */
    public Integer getNumofchildren() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.Workers.incomeID</code>.
     */
    public void setIncomeid(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.Workers.incomeID</code>.
     */
    public Integer getIncomeid() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.Workers.livealone</code>.
     */
    public void setLivealone(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.Workers.livealone</code>.
     */
    public String getLivealone() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.Workers.emcontUSAname</code>.
     */
    public void setEmcontusaname(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.Workers.emcontUSAname</code>.
     */
    public String getEmcontusaname() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.Workers.emcontUSArelation</code>.
     */
    public void setEmcontusarelation(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.Workers.emcontUSArelation</code>.
     */
    public String getEmcontusarelation() {
        return (String) get(23);
    }

    /**
     * Setter for <code>public.Workers.emcontUSAphone</code>.
     */
    public void setEmcontusaphone(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.Workers.emcontUSAphone</code>.
     */
    public String getEmcontusaphone() {
        return (String) get(24);
    }

    /**
     * Setter for <code>public.Workers.dwccardnum</code>.
     */
    public void setDwccardnum(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.Workers.dwccardnum</code>.
     */
    public Integer getDwccardnum() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>public.Workers.neighborhoodID</code>.
     */
    public void setNeighborhoodid(Integer value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.Workers.neighborhoodID</code>.
     */
    public Integer getNeighborhoodid() {
        return (Integer) get(26);
    }

    /**
     * Setter for <code>public.Workers.immigrantrefugee</code>.
     */
    public void setImmigrantrefugee(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.Workers.immigrantrefugee</code>.
     */
    public String getImmigrantrefugee() {
        return (String) get(27);
    }

    /**
     * Setter for <code>public.Workers.countryoforiginID</code>.
     */
    public void setCountryoforiginid(Integer value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.Workers.countryoforiginID</code>.
     */
    public Integer getCountryoforiginid() {
        return (Integer) get(28);
    }

    /**
     * Setter for <code>public.Workers.emcontoriginname</code>.
     */
    public void setEmcontoriginname(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.Workers.emcontoriginname</code>.
     */
    public String getEmcontoriginname() {
        return (String) get(29);
    }

    /**
     * Setter for <code>public.Workers.emcontoriginrelation</code>.
     */
    public void setEmcontoriginrelation(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.Workers.emcontoriginrelation</code>.
     */
    public String getEmcontoriginrelation() {
        return (String) get(30);
    }

    /**
     * Setter for <code>public.Workers.emcontoriginphone</code>.
     */
    public void setEmcontoriginphone(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.Workers.emcontoriginphone</code>.
     */
    public String getEmcontoriginphone() {
        return (String) get(31);
    }

    /**
     * Setter for <code>public.Workers.memberexpirationdate</code>.
     */
    public void setMemberexpirationdate(LocalDateTime value) {
        set(32, value);
    }

    /**
     * Getter for <code>public.Workers.memberexpirationdate</code>.
     */
    public LocalDateTime getMemberexpirationdate() {
        return (LocalDateTime) get(32);
    }

    /**
     * Setter for <code>public.Workers.driverslicense</code>.
     */
    public void setDriverslicense(String value) {
        set(33, value);
    }

    /**
     * Getter for <code>public.Workers.driverslicense</code>.
     */
    public String getDriverslicense() {
        return (String) get(33);
    }

    /**
     * Setter for <code>public.Workers.licenseexpirationdate</code>.
     */
    public void setLicenseexpirationdate(LocalDateTime value) {
        set(34, value);
    }

    /**
     * Getter for <code>public.Workers.licenseexpirationdate</code>.
     */
    public LocalDateTime getLicenseexpirationdate() {
        return (LocalDateTime) get(34);
    }

    /**
     * Setter for <code>public.Workers.carinsurance</code>.
     */
    public void setCarinsurance(String value) {
        set(35, value);
    }

    /**
     * Getter for <code>public.Workers.carinsurance</code>.
     */
    public String getCarinsurance() {
        return (String) get(35);
    }

    /**
     * Setter for <code>public.Workers.insuranceexpiration</code>.
     */
    public void setInsuranceexpiration(LocalDateTime value) {
        set(36, value);
    }

    /**
     * Getter for <code>public.Workers.insuranceexpiration</code>.
     */
    public LocalDateTime getInsuranceexpiration() {
        return (LocalDateTime) get(36);
    }

    /**
     * Setter for <code>public.Workers.ImageID</code>.
     */
    public void setImageid(Integer value) {
        set(37, value);
    }

    /**
     * Getter for <code>public.Workers.ImageID</code>.
     */
    public Integer getImageid() {
        return (Integer) get(37);
    }

    /**
     * Setter for <code>public.Workers.skill1</code>.
     */
    public void setSkill1(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>public.Workers.skill1</code>.
     */
    public Integer getSkill1() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>public.Workers.skill2</code>.
     */
    public void setSkill2(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>public.Workers.skill2</code>.
     */
    public Integer getSkill2() {
        return (Integer) get(39);
    }

    /**
     * Setter for <code>public.Workers.skill3</code>.
     */
    public void setSkill3(Integer value) {
        set(40, value);
    }

    /**
     * Getter for <code>public.Workers.skill3</code>.
     */
    public Integer getSkill3() {
        return (Integer) get(40);
    }

    /**
     * Setter for <code>public.Workers.datecreated</code>.
     */
    public void setDatecreated(LocalDateTime value) {
        set(41, value);
    }

    /**
     * Getter for <code>public.Workers.datecreated</code>.
     */
    public LocalDateTime getDatecreated() {
        return (LocalDateTime) get(41);
    }

    /**
     * Setter for <code>public.Workers.dateupdated</code>.
     */
    public void setDateupdated(LocalDateTime value) {
        set(42, value);
    }

    /**
     * Getter for <code>public.Workers.dateupdated</code>.
     */
    public LocalDateTime getDateupdated() {
        return (LocalDateTime) get(42);
    }

    /**
     * Setter for <code>public.Workers.Createdby</code>.
     */
    public void setCreatedby(String value) {
        set(43, value);
    }

    /**
     * Getter for <code>public.Workers.Createdby</code>.
     */
    public String getCreatedby() {
        return (String) get(43);
    }

    /**
     * Setter for <code>public.Workers.Updatedby</code>.
     */
    public void setUpdatedby(String value) {
        set(44, value);
    }

    /**
     * Getter for <code>public.Workers.Updatedby</code>.
     */
    public String getUpdatedby() {
        return (String) get(44);
    }

    /**
     * Setter for <code>public.Workers.homeless</code>.
     */
    public void setHomeless(String value) {
        set(45, value);
    }

    /**
     * Getter for <code>public.Workers.homeless</code>.
     */
    public String getHomeless() {
        return (String) get(45);
    }

    /**
     * Setter for <code>public.Workers.workerRating</code>.
     */
    public void setWorkerrating(Float value) {
        set(46, value);
    }

    /**
     * Getter for <code>public.Workers.workerRating</code>.
     */
    public Float getWorkerrating() {
        return (Float) get(46);
    }

    /**
     * Setter for <code>public.Workers.housingType</code>.
     */
    public void setHousingtype(Integer value) {
        set(47, value);
    }

    /**
     * Getter for <code>public.Workers.housingType</code>.
     */
    public Integer getHousingtype() {
        return (Integer) get(47);
    }

    /**
     * Setter for <code>public.Workers.liveWithSpouse</code>.
     */
    public void setLivewithspouse(String value) {
        set(48, value);
    }

    /**
     * Getter for <code>public.Workers.liveWithSpouse</code>.
     */
    public String getLivewithspouse() {
        return (String) get(48);
    }

    /**
     * Setter for <code>public.Workers.liveWithDescription</code>.
     */
    public void setLivewithdescription(String value) {
        set(49, value);
    }

    /**
     * Getter for <code>public.Workers.liveWithDescription</code>.
     */
    public String getLivewithdescription() {
        return (String) get(49);
    }

    /**
     * Setter for <code>public.Workers.americanBornChildren</code>.
     */
    public void setAmericanbornchildren(Integer value) {
        set(50, value);
    }

    /**
     * Getter for <code>public.Workers.americanBornChildren</code>.
     */
    public Integer getAmericanbornchildren() {
        return (Integer) get(50);
    }

    /**
     * Setter for <code>public.Workers.numChildrenUnder18</code>.
     */
    public void setNumchildrenunder18(Integer value) {
        set(51, value);
    }

    /**
     * Getter for <code>public.Workers.numChildrenUnder18</code>.
     */
    public Integer getNumchildrenunder18() {
        return (Integer) get(51);
    }

    /**
     * Setter for <code>public.Workers.educationLevel</code>.
     */
    public void setEducationlevel(Integer value) {
        set(52, value);
    }

    /**
     * Getter for <code>public.Workers.educationLevel</code>.
     */
    public Integer getEducationlevel() {
        return (Integer) get(52);
    }

    /**
     * Setter for <code>public.Workers.farmLaborCharacteristics</code>.
     */
    public void setFarmlaborcharacteristics(Integer value) {
        set(53, value);
    }

    /**
     * Getter for <code>public.Workers.farmLaborCharacteristics</code>.
     */
    public Integer getFarmlaborcharacteristics() {
        return (Integer) get(53);
    }

    /**
     * Setter for <code>public.Workers.wageTheftVictim</code>.
     */
    public void setWagetheftvictim(String value) {
        set(54, value);
    }

    /**
     * Getter for <code>public.Workers.wageTheftVictim</code>.
     */
    public String getWagetheftvictim() {
        return (String) get(54);
    }

    /**
     * Setter for <code>public.Workers.wageTheftRecoveryAmount</code>.
     */
    public void setWagetheftrecoveryamount(Double value) {
        set(55, value);
    }

    /**
     * Getter for <code>public.Workers.wageTheftRecoveryAmount</code>.
     */
    public Double getWagetheftrecoveryamount() {
        return (Double) get(55);
    }

    /**
     * Setter for <code>public.Workers.lastPaymentDate</code>.
     */
    public void setLastpaymentdate(LocalDateTime value) {
        set(56, value);
    }

    /**
     * Getter for <code>public.Workers.lastPaymentDate</code>.
     */
    public LocalDateTime getLastpaymentdate() {
        return (LocalDateTime) get(56);
    }

    /**
     * Setter for <code>public.Workers.lastPaymentAmount</code>.
     */
    public void setLastpaymentamount(Double value) {
        set(57, value);
    }

    /**
     * Getter for <code>public.Workers.lastPaymentAmount</code>.
     */
    public Double getLastpaymentamount() {
        return (Double) get(57);
    }

    /**
     * Setter for <code>public.Workers.ownTools</code>.
     */
    public void setOwntools(String value) {
        set(58, value);
    }

    /**
     * Getter for <code>public.Workers.ownTools</code>.
     */
    public String getOwntools() {
        return (String) get(58);
    }

    /**
     * Setter for <code>public.Workers.healthInsurance</code>.
     */
    public void setHealthinsurance(String value) {
        set(59, value);
    }

    /**
     * Getter for <code>public.Workers.healthInsurance</code>.
     */
    public String getHealthinsurance() {
        return (String) get(59);
    }

    /**
     * Setter for <code>public.Workers.usVeteran</code>.
     */
    public void setUsveteran(String value) {
        set(60, value);
    }

    /**
     * Getter for <code>public.Workers.usVeteran</code>.
     */
    public String getUsveteran() {
        return (String) get(60);
    }

    /**
     * Setter for <code>public.Workers.healthInsuranceDate</code>.
     */
    public void setHealthinsurancedate(LocalDateTime value) {
        set(61, value);
    }

    /**
     * Getter for <code>public.Workers.healthInsuranceDate</code>.
     */
    public LocalDateTime getHealthinsurancedate() {
        return (LocalDateTime) get(61);
    }

    /**
     * Setter for <code>public.Workers.vehicleTypeID</code>.
     */
    public void setVehicletypeid(Integer value) {
        set(62, value);
    }

    /**
     * Getter for <code>public.Workers.vehicleTypeID</code>.
     */
    public Integer getVehicletypeid() {
        return (Integer) get(62);
    }

    /**
     * Setter for <code>public.Workers.incomeSourceID</code>.
     */
    public void setIncomesourceid(Integer value) {
        set(63, value);
    }

    /**
     * Getter for <code>public.Workers.incomeSourceID</code>.
     */
    public Integer getIncomesourceid() {
        return (Integer) get(63);
    }

    /**
     * Setter for <code>public.Workers.introToCenter</code>.
     */
    public void setIntrotocenter(String value) {
        set(64, value);
    }

    /**
     * Getter for <code>public.Workers.introToCenter</code>.
     */
    public String getIntrotocenter() {
        return (String) get(64);
    }

    /**
     * Setter for <code>public.Workers.lgbtq</code>.
     */
    public void setLgbtq(String value) {
        set(65, value);
    }

    /**
     * Getter for <code>public.Workers.lgbtq</code>.
     */
    public String getLgbtq() {
        return (String) get(65);
    }

    /**
     * Setter for <code>public.Workers.typeOfWork</code>.
     */
    public void setTypeofwork(String value) {
        set(66, value);
    }

    /**
     * Getter for <code>public.Workers.typeOfWork</code>.
     */
    public String getTypeofwork() {
        return (String) get(66);
    }

    /**
     * Setter for <code>public.Workers.memberStatusEN</code>.
     */
    public void setMemberstatusen(String value) {
        set(67, value);
    }

    /**
     * Getter for <code>public.Workers.memberStatusEN</code>.
     */
    public String getMemberstatusen() {
        return (String) get(67);
    }

    /**
     * Setter for <code>public.Workers.memberStatusES</code>.
     */
    public void setMemberstatuses(String value) {
        set(68, value);
    }

    /**
     * Getter for <code>public.Workers.memberStatusES</code>.
     */
    public String getMemberstatuses() {
        return (String) get(68);
    }

    /**
     * Setter for <code>public.Workers.fullNameAndID</code>.
     */
    public void setFullnameandid(String value) {
        set(69, value);
    }

    /**
     * Getter for <code>public.Workers.fullNameAndID</code>.
     */
    public String getFullnameandid() {
        return (String) get(69);
    }

    /**
     * Setter for <code>public.Workers.skillCodes</code>.
     */
    public void setSkillcodes(String value) {
        set(70, value);
    }

    /**
     * Getter for <code>public.Workers.skillCodes</code>.
     */
    public String getSkillcodes() {
        return (String) get(70);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorkersRecord
     */
    public WorkersRecord() {
        super(Workers.WORKERS);
    }

    /**
     * Create a detached, initialised WorkersRecord
     */
    public WorkersRecord(Integer id, Integer typeofworkid, LocalDateTime dateofmembership, LocalDateTime dateofbirth, Integer memberstatus, LocalDateTime memberreactivatedate, String active, Integer raceid, String raceother, String height, String weight, Integer englishlevelid, String recentarrival, LocalDateTime dateinusa, LocalDateTime dateinseattle, String disabled, String disabilitydesc, Integer maritalstatus, String livewithchildren, Integer numofchildren, Integer incomeid, String livealone, String emcontusaname, String emcontusarelation, String emcontusaphone, Integer dwccardnum, Integer neighborhoodid, String immigrantrefugee, Integer countryoforiginid, String emcontoriginname, String emcontoriginrelation, String emcontoriginphone, LocalDateTime memberexpirationdate, String driverslicense, LocalDateTime licenseexpirationdate, String carinsurance, LocalDateTime insuranceexpiration, Integer imageid, Integer skill1, Integer skill2, Integer skill3, LocalDateTime datecreated, LocalDateTime dateupdated, String createdby, String updatedby, String homeless, Float workerrating, Integer housingtype, String livewithspouse, String livewithdescription, Integer americanbornchildren, Integer numchildrenunder18, Integer educationlevel, Integer farmlaborcharacteristics, String wagetheftvictim, Double wagetheftrecoveryamount, LocalDateTime lastpaymentdate, Double lastpaymentamount, String owntools, String healthinsurance, String usveteran, LocalDateTime healthinsurancedate, Integer vehicletypeid, Integer incomesourceid, String introtocenter, String lgbtq, String typeofwork, String memberstatusen, String memberstatuses, String fullnameandid, String skillcodes) {
        super(Workers.WORKERS);

        setId(id);
        setTypeofworkid(typeofworkid);
        setDateofmembership(dateofmembership);
        setDateofbirth(dateofbirth);
        setMemberstatus(memberstatus);
        setMemberreactivatedate(memberreactivatedate);
        setActive(active);
        setRaceid(raceid);
        setRaceother(raceother);
        setHeight(height);
        setWeight(weight);
        setEnglishlevelid(englishlevelid);
        setRecentarrival(recentarrival);
        setDateinusa(dateinusa);
        setDateinseattle(dateinseattle);
        setDisabled(disabled);
        setDisabilitydesc(disabilitydesc);
        setMaritalstatus(maritalstatus);
        setLivewithchildren(livewithchildren);
        setNumofchildren(numofchildren);
        setIncomeid(incomeid);
        setLivealone(livealone);
        setEmcontusaname(emcontusaname);
        setEmcontusarelation(emcontusarelation);
        setEmcontusaphone(emcontusaphone);
        setDwccardnum(dwccardnum);
        setNeighborhoodid(neighborhoodid);
        setImmigrantrefugee(immigrantrefugee);
        setCountryoforiginid(countryoforiginid);
        setEmcontoriginname(emcontoriginname);
        setEmcontoriginrelation(emcontoriginrelation);
        setEmcontoriginphone(emcontoriginphone);
        setMemberexpirationdate(memberexpirationdate);
        setDriverslicense(driverslicense);
        setLicenseexpirationdate(licenseexpirationdate);
        setCarinsurance(carinsurance);
        setInsuranceexpiration(insuranceexpiration);
        setImageid(imageid);
        setSkill1(skill1);
        setSkill2(skill2);
        setSkill3(skill3);
        setDatecreated(datecreated);
        setDateupdated(dateupdated);
        setCreatedby(createdby);
        setUpdatedby(updatedby);
        setHomeless(homeless);
        setWorkerrating(workerrating);
        setHousingtype(housingtype);
        setLivewithspouse(livewithspouse);
        setLivewithdescription(livewithdescription);
        setAmericanbornchildren(americanbornchildren);
        setNumchildrenunder18(numchildrenunder18);
        setEducationlevel(educationlevel);
        setFarmlaborcharacteristics(farmlaborcharacteristics);
        setWagetheftvictim(wagetheftvictim);
        setWagetheftrecoveryamount(wagetheftrecoveryamount);
        setLastpaymentdate(lastpaymentdate);
        setLastpaymentamount(lastpaymentamount);
        setOwntools(owntools);
        setHealthinsurance(healthinsurance);
        setUsveteran(usveteran);
        setHealthinsurancedate(healthinsurancedate);
        setVehicletypeid(vehicletypeid);
        setIncomesourceid(incomesourceid);
        setIntrotocenter(introtocenter);
        setLgbtq(lgbtq);
        setTypeofwork(typeofwork);
        setMemberstatusen(memberstatusen);
        setMemberstatuses(memberstatuses);
        setFullnameandid(fullnameandid);
        setSkillcodes(skillcodes);
    }
}
