/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core;


import com.savagelearning.machete.core.tables.Workersignins;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NCI_WI_WORKERSIGNINS_920345646A83399347A7 = Internal.createIndex(DSL.name("nci_wi_WorkerSignins_920345646A83399347A7"), Workersignins.WORKERSIGNINS, new OrderField[] { Workersignins.WORKERSIGNINS.DWCCARDNUM }, false);
}
