/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.Activities_id_seq</code>
     */
    public static final Sequence<Long> ACTIVITIES_ID_SEQ = Internal.createSequence("Activities_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.ActivitySignins_id_seq</code>
     */
    public static final Sequence<Long> ACTIVITYSIGNINS_ID_SEQ = Internal.createSequence("ActivitySignins_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Configs_id_seq</code>
     */
    public static final Sequence<Long> CONFIGS_ID_SEQ = Internal.createSequence("Configs_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Emails_id_seq</code>
     */
    public static final Sequence<Long> EMAILS_ID_SEQ = Internal.createSequence("Emails_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Employers_id_seq</code>
     */
    public static final Sequence<Long> EMPLOYERS_ID_SEQ = Internal.createSequence("Employers_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Events_id_seq</code>
     */
    public static final Sequence<Long> EVENTS_ID_SEQ = Internal.createSequence("Events_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Images_id_seq</code>
     */
    public static final Sequence<Long> IMAGES_ID_SEQ = Internal.createSequence("Images_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.JoinEventImage_id_seq</code>
     */
    public static final Sequence<Long> JOINEVENTIMAGE_ID_SEQ = Internal.createSequence("JoinEventImage_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Lookups_id_seq</code>
     */
    public static final Sequence<Long> LOOKUPS_ID_SEQ = Internal.createSequence("Lookups_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.Persons_id_seq</code>
     */
    public static final Sequence<Long> PERSONS_ID_SEQ = Internal.createSequence("Persons_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.ReportDefinitions_id_seq</code>
     */
    public static final Sequence<Long> REPORTDEFINITIONS_ID_SEQ = Internal.createSequence("ReportDefinitions_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.ScheduleRules_id_seq</code>
     */
    public static final Sequence<Long> SCHEDULERULES_ID_SEQ = Internal.createSequence("ScheduleRules_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.TransportCostRules_id_seq</code>
     */
    public static final Sequence<Long> TRANSPORTCOSTRULES_ID_SEQ = Internal.createSequence("TransportCostRules_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.TransportProviderAvailabilities_id_seq</code>
     */
    public static final Sequence<Long> TRANSPORTPROVIDERAVAILABILITIES_ID_SEQ = Internal.createSequence("TransportProviderAvailabilities_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.TransportProviders_id_seq</code>
     */
    public static final Sequence<Long> TRANSPORTPROVIDERS_ID_SEQ = Internal.createSequence("TransportProviders_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.TransportRules_id_seq</code>
     */
    public static final Sequence<Long> TRANSPORTRULES_ID_SEQ = Internal.createSequence("TransportRules_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.WorkAssignments_id_seq</code>
     */
    public static final Sequence<Long> WORKASSIGNMENTS_ID_SEQ = Internal.createSequence("WorkAssignments_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.WorkerRequests_id_seq</code>
     */
    public static final Sequence<Long> WORKERREQUESTS_ID_SEQ = Internal.createSequence("WorkerRequests_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.WorkerSignins_id_seq</code>
     */
    public static final Sequence<Long> WORKERSIGNINS_ID_SEQ = Internal.createSequence("WorkerSignins_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.WorkOrders_id_seq</code>
     */
    public static final Sequence<Long> WORKORDERS_ID_SEQ = Internal.createSequence("WorkOrders_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
