/*
 * This file is generated by jOOQ.
 */
package com.savagelearning.machete.core.tables;


import com.savagelearning.machete.core.Keys;
import com.savagelearning.machete.core.Public;
import com.savagelearning.machete.core.tables.records.TransportcostrulesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transportcostrules extends TableImpl<TransportcostrulesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.TransportCostRules</code>
     */
    public static final Transportcostrules TRANSPORTCOSTRULES = new Transportcostrules();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransportcostrulesRecord> getRecordType() {
        return TransportcostrulesRecord.class;
    }

    /**
     * The column <code>public.TransportCostRules.id</code>.
     */
    public final TableField<TransportcostrulesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field("nextval('\"TransportCostRules_id_seq\"'::regclass)", SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.TransportCostRules.transportRuleID</code>.
     */
    public final TableField<TransportcostrulesRecord, Integer> TRANSPORTRULEID = createField(DSL.name("transportRuleID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.minWorker</code>.
     */
    public final TableField<TransportcostrulesRecord, Integer> MINWORKER = createField(DSL.name("minWorker"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.maxWorker</code>.
     */
    public final TableField<TransportcostrulesRecord, Integer> MAXWORKER = createField(DSL.name("maxWorker"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.cost</code>.
     */
    public final TableField<TransportcostrulesRecord, Double> COST = createField(DSL.name("cost"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.datecreated</code>.
     */
    public final TableField<TransportcostrulesRecord, LocalDateTime> DATECREATED = createField(DSL.name("datecreated"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.dateupdated</code>.
     */
    public final TableField<TransportcostrulesRecord, LocalDateTime> DATEUPDATED = createField(DSL.name("dateupdated"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.TransportCostRules.Createdby</code>.
     */
    public final TableField<TransportcostrulesRecord, String> CREATEDBY = createField(DSL.name("Createdby"), SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>public.TransportCostRules.Updatedby</code>.
     */
    public final TableField<TransportcostrulesRecord, String> UPDATEDBY = createField(DSL.name("Updatedby"), SQLDataType.VARCHAR(30), this, "");

    private Transportcostrules(Name alias, Table<TransportcostrulesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transportcostrules(Name alias, Table<TransportcostrulesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.TransportCostRules</code> table reference
     */
    public Transportcostrules(String alias) {
        this(DSL.name(alias), TRANSPORTCOSTRULES);
    }

    /**
     * Create an aliased <code>public.TransportCostRules</code> table reference
     */
    public Transportcostrules(Name alias) {
        this(alias, TRANSPORTCOSTRULES);
    }

    /**
     * Create a <code>public.TransportCostRules</code> table reference
     */
    public Transportcostrules() {
        this(DSL.name("TransportCostRules"), null);
    }

    public <O extends Record> Transportcostrules(Table<O> child, ForeignKey<O, TransportcostrulesRecord> key) {
        super(child, key, TRANSPORTCOSTRULES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<TransportcostrulesRecord> getPrimaryKey() {
        return Keys.PK_DBO_TRANSPORTCOSTRULES;
    }

    @Override
    public List<UniqueKey<TransportcostrulesRecord>> getKeys() {
        return Arrays.<UniqueKey<TransportcostrulesRecord>>asList(Keys.PK_DBO_TRANSPORTCOSTRULES);
    }

    @Override
    public List<ForeignKey<TransportcostrulesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TransportcostrulesRecord, ?>>asList(Keys.TRANSPORTCOSTRULES__FK_DBO_TRANSPORTCOSTRULES_DBO_TRANSPORTRULES_TRANSPORTRULEID);
    }

    public Transportrules transportrules() {
        return new Transportrules(this, Keys.TRANSPORTCOSTRULES__FK_DBO_TRANSPORTCOSTRULES_DBO_TRANSPORTRULES_TRANSPORTRULEID);
    }

    @Override
    public Transportcostrules as(String alias) {
        return new Transportcostrules(DSL.name(alias), this);
    }

    @Override
    public Transportcostrules as(Name alias) {
        return new Transportcostrules(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transportcostrules rename(String name) {
        return new Transportcostrules(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transportcostrules rename(Name name) {
        return new Transportcostrules(name, null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Integer, Integer, Integer, Double, LocalDateTime, LocalDateTime, String, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }
}
